### ISSUE TITLE
no more hooks

### ISSUE THREAD

**Issue by aheckmann** [LearnBoost/mongoose#1446]
They belong in user land. 

Post hooks: we'll just emit events on models instead

    Model.on('update', cb)
    Model.on('save', cb)
    etc

Pre hooks: users can wrap the methods with some form of flow control themselves or maybe we'll have a third party module provide a similar standard as today. This allows us to return promises directly - see #1431

**Comment by vkarpov15** [comment]
This ticket isn't going to happen.
