### ISSUE TITLE
Middleware for update document

### ISSUE THREAD

**Issue by CodersBrothers** [LearnBoost/mongoose#1693]
What is the best option to update a document with mongoosejs? Function Find and save or update? Update don't make pre("validate") or pre("save") of schema middlewares.

Find and save:

    User.findById(userId, fields, options, function(err, userResult){

    if(err){
      return callback(err);
    }

    userResult.age = 15;

    userResult.save();

    callback(null, userResult);

    });

update:

     User.update(filter, update, options, callback);

And if you update more than one document? I need use update, but this don't make middlewares...

**Comment by vkarpov15** [comment]
4.0 now has update middleware, see release notes here: https://github.com/LearnBoost/mongoose/wiki/4.0-Release-Notes
