### ISSUE TITLE
Schema.type.Mixed and deep modification does not update document

### ISSUE THREAD

**Issue by Unitech** [LearnBoost/mongoose#1694]
When I try to update a deep nested field, the query is well sent to MongoDB but when I do a find on this doc, the field is not updated.

Example
```javascript
var DtSchema = mongoose.Schema({
     nested : Schema.type.mixed
});

var Dt = mongoose.model('Dt', DtSchema)

var test = new Dt({nested : { a : 'test', b : { c : { d : null } } } });

test.save(function(err, _test) {
    _test.nested.b.c.d = 'Hello !';
    _test.save(function(err, _test) {
       // _test is okay, the field nested.b.c.d is updated 
       
       Dt.findOne({_id : _test._id}, function(err, doc) {
           // Here The doc has not the nested.b.c.d field updated
       });
    })
});
```

**Comment by yanCode** [comment]
markModified works well for me, with "mongoose": "~3.8.14" on Mac os.

**Comment by gregwym** [comment]
Thanks, `markModified` is really useful in this case.

**Comment by tomerb15** [comment]
what about 1 level further, markModified didn't work in my case:
mongoose scheme:
```
var restsSchema = new Schema({
    name: String,
    menu: mongoose.Schema.Types.Mixed
});
```
simplfied document:
```
{
    name: "Dominos Pizza",
    menu:{
             "1":{
                  name: "Plain Pizza",
                  soldCounter: 0
               },
             "2":{
                  name: "Pizza with vegetables",
                  soldCounter: 0
                }
         }
}
```

I'm trying to update the soldCounter when given a single/array of menu items as followed:
```
function(course, rest){
        rest.markModified("menu.1");
        db.model('rests').update({_id: rest._id},{$inc:{"menu.1.soldCounter":1}});
```

once this will work i obviously will want to make it more generic, something like: (this syntax is not working)
```
function(course, rest){
        rest.markModified("menu." + course.id);
        db.model('rests').update({_id: rest._id},{$inc:{"menu.+"course.id"+.soldCounter":1}});
```

any one can help with this one?

**Comment by vkarpov15** [comment]
Why are you using `markModified()` with `update()`? Those two don't have anything to do with each other.

**Comment by tomerb15** [comment]
Nothing from the functions above will work, but I wanted it to clear what I'm trying to achieve. 

I also have no problem changing the scheme so that 'menu' will be an indexed array of types.Mixed

**Comment by YanLobat** [comment]
`markModified()` causes this: `VersionError: No matching document found.`

**Comment by bhagaban** [comment]
If you do this, it will work.

var nested = JSON.parse(JSON.stringify(_test.nested));
//now changed the nested object.
nested.a = "new value"
_test.nested = nested;
_test.save();

**Comment by Abdulkadir98** [comment]
@bhagaban Thank you so much! Just when I thought I had tried everything. Your code worked wonderfully.
