### ISSUE TITLE
Using lean for save?

### ISSUE THREAD

**Issue by imrefazekas** [LearnBoost/mongoose#1723]
I would like to use lean option as for save.
The callback of save returns also a mongoose document and not a JS object which I want to change using a lean-like call.

Using lean for queries and toObject in saves' callback functions seems like a confusion to me.

Any ideas?

**Comment by ORESoftware** [comment]
hummity hums...save should have a lean option

**Comment by vkarpov15** [comment]
How would you imagine save() and lean working together? AFAIK that doesn't make sense.

**Comment by ORESoftware** [comment]
ummm, it's a been a few days but.

```js
user.save(function(err,user){

      //user is full-fledged etc
});
```

with lean option, it would be

```js
user.save(function(err,user){

      //user is *not* full-fledged etc
});
```

isn't that right?

**Comment by vkarpov15** [comment]
@ORESoftware nope, because the 2nd parameter in the callback to save is the exact same document. Mongoose doesn't ask the database for the newly updated doc. For instance,

```javascript
user.save(function(err, _user){
  user === _user; // true
});
```

**Comment by ORESoftware** [comment]
oh ok got it :)

**Comment by peterpeterparker** [comment]
for the record, the solution provided above by @refack still work like a charm in 2017

**Comment by alex-dixon** [comment]
@peterpeterparker I disagree and think this is still an issue for users who want data to be returned from all database operations instead of Mongoose instances.

**Comment by peterpeterparker** [comment]
@alex-dixon I was just pointing out that the solution of @refack for the `save` operation is still valid and functional in 2017, nothing more, nothing less ;)

**Comment by alex-dixon** [comment]
@peterpeterparker You're right. Sorry. Shouldn't have directed that toward you.

**Comment by peterpeterparker** [comment]
@alex-dixon no worries

**Comment by ORESoftware** [comment]
should we use `lean()` with `Model.create()`?

**Comment by vkarpov15** [comment]
Never because you can't use `lean()` with `Model.create()` :p

**Comment by ORESoftware** [comment]
got it :)

**Comment by Phpfox-regimental1** [comment]
Look here for the answer https://jquery-jscrollpane-prick.github.io/VMfa8Lysmss32weG4hGckWN6sWIv-Vi3pubJYKplwzyk02yjQhZz11hDIQjAhA/
