### ISSUE TITLE
Feature Request: Schema default populate rules

### ISSUE THREAD

**Issue by caitp** [LearnBoost/mongoose#1733]
So [this](http://stackoverflow.com/questions/19287142/populate-a-mongoose-model-with-a-field-that-isnt-an-id) was asked on StackOverflow today.

Essentially they're wanting to reference a foreign document by a field other than ID.

I'm not sure how common of a use case this is, and obviously it wouldn't be very useful in many cases. However, it seems inconvenient to require developers to use the populate API manually for virtually every single query to that model.

So, yeah it's not totally NoSQL to do this, but at the same time it's sometimes important to minimize redundancy, and provide a more normalized model.

Solutions that I've come up with for the problem:

1. **Static function (no patch needed)**
Simply create a static method which would perform the correct population as needed, saving trouble for developers while still keeping improved performance in the more common use cases.

2. **Schema options defining "default" population rules**
Being able to simply say document.populate() with no arguments could automatically use rules defined by Schema options, such as search queries, or other rules to essentially perform a _join_. Again, not terribly NoSQL, but still incredibly convenient, and would also minimize the number of lines of code which would need to be updated if the model changed.

I'm not sure which approach is better. I mean for the typical nosql approach you want to avoid joins as much as possible, but clearly there are people who would like this sort of thing, and convenience is a plus, even if there's a bit of a performance cost.

I'm not sure what to say about it, thought I'd throw it out there and see if anyone thought it was worth implementing, or if there's already a better way.

**Comment by Farcek** [comment]
+1

**Comment by vkarpov15** [comment]
See https://www.npmjs.com/package/mongoose-autopopulate .
