### ISSUE TITLE
`authdb` option not working

### ISSUE THREAD

**Issue by frty2** [LearnBoost/mongoose#1740]
using 

        var connectionString = 'mongodb://' + config.database.username + ':' + config.database.password + '@' + config.database.host + ':' + config.database.port + '/' + dbname;
        var connection = mongoose.createConnection(connectionString);

everything is replaced fine. user is create via mongo shell db.addUser() and has role 'readWriteAnyDatabase'. User can connect via mongo shell and query the db. But not via mongoose.

        MongoError: not authorized for query on punch.shops
        >>     at Object.toError (/var/www/virtual/punch/html/punch/node_modules/mongoose/node_modules/mongodb/lib/mongodb/utils.js:110:11)
        >>     at /var/www/virtual/punch/html/punch/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:634:54
        >>     at Cursor.close (/var/www/virtual/punch/html/punch/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:903:5)
        >>     at commandHandler (/var/www/virtual/punch/html/punch/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:634:21)
        >>     at /var/www/virtual/punch/html/punch/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1670:9
        >>     at Server.Base._callHandler (/var/www/virtual/punch/html/punch/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
        >>     at /var/www/virtual/punch/html/punch/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
        >>     at MongoReply.parseBody (/var/www/virtual/punch/html/punch/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
        >>     at null.<anonymous> (/var/www/virtual/punch/html/punch/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
        >>     at EventEmitter.emit (events.js:95:17)
        >> Exited with code: 8.

**Comment by vkarpov15** [comment]
No response for a while, reopen if this is still an issue.

**Comment by johnkors** [comment]
still an issue. Can connect thru mongo 3.0 shell, but not thru mongoose

**Comment by vkarpov15** [comment]
What do your connection options look like @johnkors ?

**Comment by johnkors** [comment]
Not sure what happened, but I rolled back to 3.8.25 and everything worked fine. Not sure how I got an unstable nightly from npm. Now using ^3.8.25

**Comment by BadLambdaJamma** [comment]
This is an issue for me using mongoose 4.01 or 4.0.6  I can not connect to Mongo when using authorization. Looking at the mongo logs  it appears that the connection is never authenticated

I see authorization for many connections in the mongo log:
[conn30]  authenticate db: xxxx { authenticate: 1, user: "xxx", nonce: "xxx", key: "xxx" }

But I never see this authentication message like I do for other connection numbers and it is the failure connection:
[conn44] assertion 13 not authorized for query  - connection 44 is never authenticated according to the logs

Turning off auth in mongo config make this problem goes away.

**Comment by vkarpov15** [comment]
@BadLambdaJamma what do your connection options look like and what auth options are you configuring mongod with?

**Comment by BadLambdaJamma** [comment]
I can use the identical connection string below (with proper username and pass) in the RoboMongo GUI application and connect properly and query collections etc. We are authorizing in the same database we connect to as this is how our PaaS provider allows access. (e.g. no admin db access)

connection code:
    mongoose.connect( 'mongodb://user.pass@services:27017/databasename');
    db = mongoose.connection
    db.on('error', console.error.bind(console, 'connection error:'));
    db.once('open', function (callback) {.......

mongod.conf:
auth = true
bind_ip = 0.0.0.0
dbpath = /var/lib/mongodb
fork = false
logappend = true
logpath = /var/log/mongodb/mongodb.log
nojournal = false
port = 27017
rest = false
smallfiles = false

**Comment by BadLambdaJamma** [comment]
my apologies, I had a malformed connection string that was still connecting but without auth.

**Comment by bgSosh** [comment]
@johnkors - are you still having this problem?  We seem to have encountered it too...

**Comment by BadLambdaJamma** [comment]
I would assume you have a malformed connection string.  To test, connect to a mongo instance that does not require authorization. (and hence you wont pass a username and password and hence your string will be simple and hard to malform).  I discovered our problem by single stepping sources.

**Comment by ddimitrov90** [comment]
i got the same prblem with version 4.4.1 
here is the connection -
var connection = mongoose.createconnection('mongodb://siteUserAdmin:password@localhost:37017/TestDB?authSource=admin');

and i get the following error:
not authorized for query on TestDB.system.indexes

i can successfully connect through the shell:
mongo --port 37017 -u siteUserAdmin -p password --authenticationDatabase admin

here is the user:
> use admin                                              
switched to db admin                                     
> show users                                             
{                                                        
        "_id" : "admin.siteUserAdmin",                   
        "user" : "siteUserAdmin",                        
        "db" : "admin",                                  
        "roles" : [                                      
                {                                        
                        "role" : "userAdminAnyDatabase", 
                        "db" : "admin"                   
                }                                        
        ]                                                
}                                                        

mongo version is 2.6.9

**Comment by BadLambdaJamma** [comment]
Step into sources for the connection string parsing.  You will see the issue right away.

**Comment by vkarpov15** [comment]
@BadLambdaJamma can you please clarify that?

**Comment by ddimitrov90** [comment]
i don't see what is wrong with the uri
i successfully authenticate here
`_this.db.authenticate(_this.user, _this.pass, _this.options.auth, function(err) {` lib\connection:516

no error and i get a connection and then when i call 
`var model = connection.model(collectionName, applicationsSchema);
            model.ensureIndexes(`

i receive the "not authorized for query" error

**Comment by vkarpov15** [comment]
@ddimitrov90 does the user that you're logged in with have permission to create indexes? That would explain the issue you're seeing.

**Comment by ddimitrov90** [comment]
@vkarpov15 you were right, the "userAdminAnyDatabase" is basically for managing users, i've create another user with the correct role for read/write access to the database and everything is working as expected
thanks

**Comment by wayofthefuture** [comment]
Just put ?authSource=admin at the end of the connection url
