### ISSUE TITLE
Multiple validation calls

### ISSUE THREAD

**Issue by Volox** [LearnBoost/mongoose#1743]
Hi,
i am experiencing an odd behaviour with the validation af subdocuments.
i've also created a gist with a mocha failing test [here](https://gist.github.com/Volox/7041207).

In my test i noticed that the `Control.test` validator is called 2 times, instead of one. I am missing something important that I should know?

Versions:
- node 10.18
- mongoose 3.6.20
- mongo 2.0

TL;DR;
validation in subdocuments is called too many times.

**Comment by vkarpov15** [comment]
This issue is fixed, test succeeds in 3.9.x
