### ISSUE TITLE
How to run Model.mapReduce and target secondary in a replica-set for read?

### ISSUE THREAD

**Issue by pgilad** [LearnBoost/mongoose#1849]
Setting read preferences on the query level is possible, but how do you do it on the Model.mapReduce level?
Obviously we are setting `out:{inline:1}` and will be writing results to the primary.

I found absolutely no documentation for it in Mongoose or MongoDB for that matter. Does that mean it isn't possible?

**Comment by nolanamy** [comment]
@pgilad Where did this end up? I'm looking for the option myself; it looks like the [node-mongodb-native](http://mongodb.github.io/node-mongodb-native/api-generated/collection.html#mapreduce) driver does support setting a `readPreference`, but Mongoose doesn't?

**Comment by vkarpov15** [comment]
Don't know off the top of my head, but I'll look into this

**Comment by nolanamy** [comment]
@vkarpov15 Thanks! Find anything?

**Comment by vkarpov15** [comment]
Nope, I had forgotten about this. But now that its on a milestone I won't forget :)

**Comment by vkarpov15** [comment]
Should work, [mapReduce docs](http://mongoosejs.com/docs/api.html#model_Model.mapReduce) say that all options are delegated to the driver. I added better documentation that says you can explicitly specify a `readPreference` option in your mapReduce calls:

```javascript
MyModel.mapReduce({ readPreference: 'secondary' }, function(err, results) {
});
```
