### ISSUE TITLE
Checking/error reporting for undefined or missing subdoc schemas

### ISSUE THREAD

**Issue by davidemannone** [LearnBoost/mongoose#1986]
I've experienced that defining a schema such that:

SchemaBefore = new Schema{"schemaafter": [SchemaAfter]};
SchemaAfter = new Schema{"anyproperty": ...};

brings all to work without errors, but the embedded schema dosn't work as expected.

Obviously this happens because SchemaAfter is not already defined, so it behaves as a ["undefined"]. This leads to wast a big amount of time the first times it happens expecially when combined with code like validators, getters/setters, defaults, and so on.

Is there any reason you do not throw an excpetion for a not defined/undefined subschema property? If someone models their own ODM architecture, then it's really difficult to immagine that he specifies definitions just as a writing exercices. Do you agree? And it could still remain the difference by letting the "anysubdoc": [], still allowed with any futher advice: in this case the intent is maybe clear to the creator.

**Comment by vkarpov15** [comment]
This is fixed in 3.9.x.
