### ISSUE TITLE
near(...) using a coordinate pair instead of a GeoJSON object doesn't work

### ISSUE THREAD

**Issue by stevelorimer** [LearnBoost/mongoose#2111]
I have coordinate pairs stored in a document, and am trying to use `qry.where(...).near(...)` to locate them.

My query returns no results.

My schema, with a static function which performs the query:

    var ModelSchema = new Schema({
        type : { type: String, index: true },
        loc  : { type: [Number], index: '2dsphere' }
    });

    ModelSchema.index({type: 1, loc: 1});

    ModelSchema.statics.search = function(search, cb) {
        var qry = this.find();
        if (search.types) {
            qry.where('type').in(search.types);
        }
        if (search.loc) {
            qry.where('loc').near({
                center: search.loc,
                maxDistance: search.distance * 1000
            });
        }
        qry.exec(cb);
    };

The query I execute is:

    Model.search({loc: [ 10, -20 ], distance: 1}, function(err, items) { ... }

I have enabled `mongoose.set('debug', true)`, and can see the resulting debug:

Inserting 2 documents in the collection with coordinates `[ 10, -20 ]`:

    Mongoose: models.insert({ _id: ..., loc: [ 10, -20 ], type: 'apple' }) {}  
    Mongoose: models.insert({ _id: ..., loc: [ 10, -20 ], type: 'orange' }) {}  

Searching for documents near coordinates `[ 10, -20 ]`:

    Mongoose: models.find({ loc: { '$near': [ 10, -20 ], '$maxDistance': 1000 } })

I'm getting back no results - is this a bug, or am I not using `qry.where(...).near(...)` properly?

**Comment by efkan** [comment]
+1

**Comment by efkan** [comment]
Hello @stevelorimer ,

The below codes works for me. Have a nice day..

    query
    .where({'location.geometry': 
        { 
	    $near: 
	        {
		    $geometry: { "type": "Point", "coordinates": [-105.01621, 39.57422] },
		    $maxDistance: 450  
		}
	    }
    })

**Comment by vkarpov15** [comment]
I think you need to specify `spherical: true` in your legacy coordinates query:

```javascript
        qry.where('loc').near({
            center: search.loc,
            maxDistance: search.distance * 1000,
            spherical: true // important
        });
```

But overall, legacy coordinate pairs are called legacy coordinate pairs for a reason. I'd recommend using GeoJSON as you specified.

**Comment by narendeveloper1** [comment]
Thanks @skebanga This Help me.

Mongoose: models.find({ loc: { '$near': { 
    '$maxDistance': 1,
    '$geometry': { type: 'Point', coordinates: [ 10, -20 ] } } } 
}) { fields: undefined }
