### ISSUE TITLE
Unable to distinguish upserted documents when using $setOnInsert option

### ISSUE THREAD

**Issue by skotchio** [LearnBoost/mongoose#2118]
I try to make the following update:

    Model.findOneAndUpdate({
      name: 'John' 
    }, {$setOnInsert: {key: value}}, {upsert: true, new: true}, function (err, doc) {
         console.log(doc.isNew)  // always true either document upserted or don't
    });

Either requested document exists or not we get isNew always true.
Or it's better is pass getLastError object in callback http://docs.mongodb.org/manual/reference/method/db.collection.update/#successful-results ?

**Comment by vkarpov15** [comment]
So actually, looking into this, this is not something I'm going to fix. The `isNew` field's semantics are that its true if and only if the document hasn't been saved to the db yet. If it upserts, the document is clearly saved to the db. As a workaround, if you use `new: false`, doc will be [null if it was an upsert](http://docs.mongodb.org/manual/reference/method/db.collection.findAndModify/). Furthermore, if you specify `new: true`, there really is no way for mongoose to know if it was a new document or not: MongoDB findAndModify only returns the document, not any metadata related to the operation.
