### ISSUE TITLE
Querying an array of dates with $elemMatch fails when using a string instead of a date object

### ISSUE THREAD

**Issue by wlingke** [LearnBoost/mongoose#2199]
For instance, if I had a schema:

```
{
    dates: [Date]
}

```

The following query will not return any results
```
{
    dates: {
        $elemMatch:{$gt: '2014-07-01T04:00:00.000Z'}
    }
}
```

Instead you must do this to get the right results:
```
{
    dates: {
        $elemMatch:{$gt: new Date('2014-07-01T04:00:00.000Z')}
    }
}
```

I have not tested this with other types, but it would seem the string is not being caste to the right type.

EDIT: I should date string works as expected if it's just one level (ie without $elemMatch).

**Comment by sidgujrathi** [comment]
This issue is still exists.
I am using `-- mongoose@4.13.11` and my query with $elemmatch still fires date as string and not as Date()

Did I missed something or do I need to install any different version?

**Comment by vkarpov15** [comment]
@sidgujrathi please open up a separate issue with code samples. This particular issue is fixed, test case has been passing for years
