### ISSUE TITLE
model.save() callback function misses numbersAffected param

### ISSUE THREAD

**Issue by robertwachtel** [LearnBoost/mongoose#2205]
```javascript
myModel.save(function(err, doc, numbersAffected) {
  console.log(typeof numbersAffected); // Results in 'undefined'
});
```
Results in 'undefined'

mongoose 3.9.0
nodejs 0.10.29
mongo 2.6.3

**Comment by vkarpov15** [comment]
Hmm the following standalone script outputs 'number' for me just fine on 3.9.0 and 4.0.0-rc3.

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var util = require('util');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/gh2205');

var s = new Schema({ name: String });
var M = mongoose.model('gh2205', s, 'gh2205');

var m = new M();
m.save(function(err, doc, num) {
  console.log(typeof num);
});
```

Perhaps you're getting a validation error?

**Comment by robertwachtel** [comment]
In fact in later builds I couldn't reproduce this behaviour. Sorry for not
closing this issue.

Viele Grüße von den Glanzkindern aus Köln

Robert Wachtel

Robert Wachtel

Diplom-Wirtschaftsinformatiker

Leiter IT/Softwareentwicklung

Tel. +49 221 310637-10 Fax +49 221 310637-40 Mobil +49 151 64930315 Email:
robert.wachtel@glanzkinder.com

2015-03-09 21:10 GMT+01:00 Valeri Karpov <notifications@github.com>:

> Hmm the following standalone script outputs 'number' for me just fine on
> 3.9.0 and 4.0.0-rc3.
>
> var mongoose = require('mongoose');var Schema = mongoose.Schema;var util = require('util');
>
> mongoose.set('debug', true);
> mongoose.connect('mongodb://localhost/gh2205');
> var s = new Schema({ name: String });var M = mongoose.model('gh2205', s, 'gh2205');
> var m = new M();
> m.save(function(err, doc, num) {
>   console.log(typeof num);
> });
>
> Perhaps you're getting a validation error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LearnBoost/mongoose/issues/2205#issuecomment-77931769>
> .
>

-- 



glanzkinder gmbh

köhlstraße 10 | 50827 köln 

fon: +49 221/310 637-10

fax: +49 221/310 637-40

www.glanzkinder.com

<https://www.seem-manager.com>

Glanzkinder GmbH

Sitz der Gesellschaft: Köln

HRB 60591 Köln

Geschäftsführer: Heinz Ingensiep

Diese E-Mail und alle mitgesendeten Dateien sind vertraulich und 
ausschließlich für den Gebrauch durch den Empfänger bestimmt!

This e-mail and any files transmitted with it are confidential intended 
solely for the use of the addressee!
