### ISSUE TITLE
doc.validate() thinks every value is undefined.

### ISSUE THREAD

**Issue by natives** [LearnBoost/mongoose#2222]
Mongoose v3.8.14
I cannot seem to get the doc.validate call to work. I fetch the document using findById (also tried findOne) and then do a doc.validate() call and it tells me that 'title is required' even though I'm console logging it before and its set:

    var self = this;
    self.findById(id, function (err, doc) {
      if (err) return callback(err);
      if (!doc) {
        return callback(new Error('Could not update document, document not found.'));
      }

      console.log(doc.title, doc._doc.title, doc.get('title'));

      // Validate the document
      doc.validate(function (err) {
        console.log(err);
        return callback(err);
      });
    });

And it's coming out as:

    sofis cloned app sofis cloned app sofis cloned app

The validation error is:

    {
      message: 'Validation failed',
      name: 'ValidationError',
      errors: 
       {
        title: {
          message: 'Path `title` is required.',
          name: 'ValidatorError',
          path: 'title',
          type: 'required',
          value: undefined
        }
      }
    }

Title property on schema:

    title: { type: String, default: "", required: true }

**Comment by vkarpov15** [comment]
No response for a while, closing. Re-open if this is still an issue.
