### ISSUE TITLE
Discussion: Why are transforms not executed when calling toObject/toJSON with any options arguments

### ISSUE THREAD

**Issue by skaapgif** [LearnBoost/mongoose#2245]
According to the documentation at http://mongoosejs.com/docs/guide.html#toObject:
> Documents have a toObject method which converts the mongoose document into a plain javascript object. This method accepts a few options. Instead of applying these options on a per-document basis we may declare the options here and have it applied to all of this schemas documents by default.

Which would lead you to believe that unless overwritten, these options will always be applied.

However, according to http://mongoosejs.com/docs/api.html#document_Document-toObject
> Note: if you call toObject and pass any options, the transform declared in your schema options will *not* be applied. To force its application pass transform: true

Which seem to contradict the behaviour of all other schema options.

As far as I understand, one of the big use cases for transforms is as a convenient way/hook to hide certain fields from further upstream. With the current mongoose implementation, a plugin like
@mblarsen https://github.com/mblarsen/mongoose-hidden would only work if you always call toObject/toJSON without any arguments. So ```myModel.toObject({minimize: false})``` will suddenly reveal hidden fields.

Is there a reason mongoose doesn't follow the following pattern:
```js
myUserSchema.set('toObject', { transform: hidePasswordTransform });
...
myUser.toObject() // Transform applied
myUser.toObject({minimize: false}) // Transform applied
myUser.toObject({transform: false}) // Transform *not* applied
```

**Comment by toebu** [comment]
This would indeed be great to have. I would have also assumed that transforms are always applied if not explicitly turned off. I guess this won't make it into 3.x since it's a breaking change.

**Comment by vkarpov15** [comment]
I'm gonna argue that this change shouldn't happen. Transforms are special in that they're dependent on all the other options: say you have a transform that assumes virtuals are on, but you try to do `toObject()` with virtuals off. If you want to pass options to `toObject()` and still use `mongoose-hidden`, just specify `{ transform: true }` in your options, like `myModel.toObject({ minimize: false, transform: true });`

**Comment by toebu** [comment]
Don't you have access to all the options in your transform? It should be the responsibility of the person writing the transform to check for any other options that the transform depends on and behave correctly based on these options.

I'm using transforms heavily to convert mongoose objects to data that can be passed through a JSON API. I'm relying on the fact that the transform is always executed to for example never expose security/privacy related data. At the same time, I need to pass in options to specify whether or not to for example include populated data from other models. It seems highly likely that someday somewhere a dev will forget to specify `{ transform: true }` and expose data that shouldn't be exposed.

**Comment by vkarpov15** [comment]
Thanks for the good argument @toebu. I also spoke briefly with @diegonetto about this today and he also argued it was fairly counterintuitive. I'm convinced enough to put in a PR and see what I think of it tomorrow :)

**Comment by toebu** [comment]
Great, happy that this is going to happen!
