### ISSUE TITLE
.save() throws expection when using with co / koajs

### ISSUE THREAD

**Issue by michelalbers** [LearnBoost/mongoose#2371]
Hi,

I use the latest master release in my koajs project and I encountered some strange issue:

```JavaScript
try {
  userToSave = new User(body.user);
  (yield userToSave.save());
  return this.body = [userToSave._id];
} catch (_error) {
  e = _error;
  return this["throw"](500, e);
}
```

In my tests im trying to actively save a User which will not pass validation. Mongoose then throws an error:  ```No listeners detected, throwing. Consider adding an error listener to your connection.```

Even though I wrapped my ```JavaScript yield userToSave.save()``` statement in try-catch block the exception cannot be caught and therefore crashes my application :-1: 
 
Isn't that contradictionary to the promise pattern? Shouldn't it simply call Promise.reject and not throw an exception on it's own?

The part in mongoose causing this (**lib/document.js:1433**):

```JavaScript
Document.prototype.$__handleReject = function handleReject(err) {
  // emit on the Model if listening
  if (this.listeners('error').length) {
    this.emit('error', err);
  } else if (this.constructor.listeners && this.constructor.listeners('error').length) {
    this.constructor.emit('error', err);
  } else if (this.listeners && this.listeners('error').length) {
    this.emit('error', err);
  } else if (this.db) {
    // emit on the connection
    if (!this.db.listeners('error').length) {
      err.stack = 'No listeners detected, throwing. Consider adding an error listener to your connection.\n' + err.stack
    }
    this.db.emit('error', err);
  } else {
    throw err;
  }
}
```

**Update: Even when using the classic callback approach, the exceptions gets thrown. That can't be right or can it be?**

Best,
Michel

**Comment by joetconcur** [comment]
I also encounter this issue where the exception still get past the try catch around save() function and crash the process. Like justin-lau mentioned above, the model level error listener does not catch that exception. The exception in my case was thrown in my custom validation function.

**Comment by vkarpov15** [comment]
Thanks @justin-lau, debugged it for me :) looks like its tricky to determine if there are listeners or not when using yield, so I'm just gonna get rid of that exception.
