### ISSUE TITLE
Using ES6 Promise.all() with Mongoose

### ISSUE THREAD

**Issue by chrisveness** [LearnBoost/mongoose#2412]
I'm not sure if this is a Mongoose question or an mpromise question, but is there any way to use (or to shim) the forthcoming ES6/Harmony Promise.all() method with Mongoose?

**Comment by albertorestifo** [comment]
@vkarpov15 is the `3.9.x` release going to use the standard ES6 Promise API?

**Comment by vkarpov15** [comment]
Nope, right now 4.0 release will only support [mpromise](https://npmjs.org/package/mpromise), which supports Promises/A+ spec but not the ES6 API, which is a whole different beast and wasn't really mature when mongoose decided to use mpromise. Ability to use your ES6 promises library of choice is a feature that's on the roadmap for the next few months though #2688

**Comment by agjs** [comment]
Would be really amazing indeed to see mongoose fully supporting es6 promises. Looking forward seeing this in a close future :)...
