### ISSUE TITLE
mongoose is removing empty object when embedded schema is defined, although minimize:false is used

### ISSUE THREAD

**Issue by ekeren** [LearnBoost/mongoose#2433]
notice the following code, that shows a schema with 2 arrays, one is configured to be from Type mongoose.Schema.Types.Mixed and one is configured to be from type {value: mongoose.Schema.Types.Mixed}

var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
var schema  = new mongoose.Schema({
  withSchema:       [{value:mongoose.Schema.Types.Mixed} ],  
  withoutSchema:  [mongoose.Schema.Types.Mixed],
} , {minimize: false});
var Tweak = mongoose.model('tweak', schema );
var data = { 
  "withSchema"    : [ { "value": { v:"221", empty:{} } } ],
  "withoutSchema" : [ { "value": { v:"221", empty:{} } } ] 
} 
Tweak.findByIdAndUpdate("545680170960023a185ea77e", data, function(err, doc){
  console.log(doc.withSchema[0].value.empty);// will print undefined
  console.log(doc.withoutSchema[0].value.empty); // will print {}
});

The empty key is removed in the withSchema although I use minimize: false

**Comment by vkarpov15** [comment]
So the issue is that mongoose treats `withSchema` as a document array, and so it has [its own schema options](http://mongoosejs.com/docs/subdocs.html#altsyntax) that don't inherit from its parent. In other words, its not really a bug so much as it is a feature of mongoose 3. You can declare a separate schema and set minimize: false there as well:

```javascript
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

var nested = new mongoose.Schema({
  value: mongoose.Schema.Types.Mixed
}, { minimize: false });

var schema = new mongoose.Schema({
  withSchema: [nested],
  withoutSchema: [mongoose.Schema.Types.Mixed],
}, {minimize: false});

var Tweak = mongoose.model('tweak', schema );
var data = { 
"withSchema" : [ { "value": { v:"221", empty:{} } } ],
"withoutSchema" : [ { "value": { v:"221", empty:{} } } ] 
} 

var t = new Tweak();
t.save(function(err, t) {
  console.log(err);
  Tweak.findByIdAndUpdate(t._id, data, function(err, doc){
    console.log(doc.withSchema[0].value.empty);// will print {} as desired
    console.log(doc.withoutSchema[0].value.empty); // will print {}
  });
});
```

**Comment by vkarpov15** [comment]
This may be improved in the future, but it'll be a big backwards breaking change unfortunately.
