### ISSUE TITLE
toObject does not apply inline transformation

### ISSUE THREAD

**Issue by dimik** [LearnBoost/mongoose#2440]
I have the following schema
```javascript
module.exports = new Schema({
  ...
}, { toObject { getters: true } });
```

in my http handler i try to remove some internal fields

```javascript
res.status(201).json(
  feature.toObject({
    getters: true,
    transform: _transformFeature
  })
);

function _transformFeature(doc, ret, options) {
  Object.keys(ret)
    .forEach(function (key) {
      if(key[0] === '_') {
        delete ret[key];
      }
    });

  return ret;
}
```

I discovered that _transformFeature not even executed because it reassigns transform field to "undefined" here
https://github.com/LearnBoost/mongoose/blob/master/lib/document.js#L1630

**Comment by chmanie** [comment]
Unfortunately this breaks stuff for me.
If I have a parent document with a transform function and a  subdocument with a transform function the child's transform function is applied to the parent and the parent's transform function is not called at all.

**Comment by vkarpov15** [comment]
Moved to a separate issue. Thanks @chmanie
