### ISSUE TITLE
Arrays saved as objects

### ISSUE THREAD

**Issue by trueinsider** [LearnBoost/mongoose#2442]
node: 0.10.33
mongodb: 2.6.5
mongoose: 3.8.18

I had a schema without an array in it. Then schema changed and now there is an array. I make changes to an array and it becomes an object. Why?

I expect that the code below would print:

	[{ value: 1 }]

Instead, it prints:

	[{ '0': { value: 1 }, value: 0 }]

Code:

	var cluster = require('cluster');
	var mongoose = require('mongoose');
	mongoose.connect('mongodb://localhost/test');
	//mongoose.set('debug', true);

	if (cluster.isMaster) {
		var schema = new mongoose.Schema({});

		var Model = mongoose.model('Model', schema);

		new Model().save(function (err, model) {
			cluster.fork({id: model.id});
		});
	} else {
		var schema = new mongoose.Schema({
			array: {
				type: [{
					_id: false,
					value: {
						type: Number,
						default: 0
					}
				}],
				default: [{}]
			}
		});

		var Model = mongoose.model('Model', schema);

		var id = new mongoose.Types.ObjectId(process.env.id);

		Model.findById(id, function (err, model) {
			model.array[0].value = 1;

			model.save(function () {
				Model.findById(id, function (err, model) {
					console.log(model.array);
				});
			});
		});
	}

**Comment by vkarpov15** [comment]
So first, I can't repro with the code you provided. I can repro it once I make it so the document that's saved in mongodb has a non-array `array` field:

```javascript
var cluster = require('cluster');
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
//mongoose.set('debug', true);

if (cluster.isMaster) {
    var schema = new mongoose.Schema({ array: mongoose.Schema.Types.Mixed }, { minimize: false });

    var Model = mongoose.model('Model', schema);

    // Make it so array is an object in the db
    new Model({ array: {} }).save(function (err, model) {
        cluster.fork({id: model.id});
    });
} else {
    var schema = new mongoose.Schema({
        array: {
            type: [{
                _id: false,
                value: {
                    type: Number,
                    default: 0
                }
            }],
            default: [{}]
        }
    });

    var Model = mongoose.model('Model', schema);
    var id = new mongoose.Types.ObjectId(process.env.id);

    Model.findById(id, function (err, model) {
        //model.array = [{ value: 1 }];
        model.array[0].value = 1;
        model.save(function () {
            Model.findById(id, function (err, model) {
                console.log(model.array);
            });
        });
    });
}
```

You can work around this by using `model.array = [{ value: 1 }];` instead of `model.array[0].value = 1;` as shown above. I'm investigating right now why this is happening though.

**Comment by murphman300** [comment]
Hello,
I seem to be running into this issue as well, almost identically. Except with a twist. (the setting is i'm saving locations, and each location has entries that are called 'days' structured as follows). I'm working in a database where each location has it's own collection, and each day, and document is entered into the collection. At first I had some arrays nested one level deep. I ran into this issue, and thought maybe if i put the arrays at the top level of the models, then it wouldn't happen, but i seem to be running into this issue still. 

I've put together that allow me to fetch, manage connections, and modify variables that are not nested within arrays.. but whenever i make an initial insert into an array, it's transformed into an object with just and ObjectID..

for example, here is the code i use to create a model reference to a specific collection:

`var visitor = new mongoose.Schema({
    usid : {type: String, require: true},
    ///And some other variables...
});`

In this case i get an object which matches the schema, i check that the required values do exist etc.
eventually..

`db.getCollection({//Parameters...
                name : content.nameOfCollection,
                model : newDay,
                dbid : location.current_day.dbid,
                tagValue : location.current_day.dateTag+content.nameOfCollection
            }, function (dbmodel) { //Here i get the model linked to the collection inside the DB..
                if (!dbmodel) return result('recieved null');
                dbmodel.reference.findOneAndUpdate({dbid : location.current_day.dbid, day_tag: location.current_day.dateTag}, {
                    'visitors' : {
                        "$push" : visitor
                    }
                }, function (err, doc) {
                    if (err) {
                        return result('Saving error: ' + err);
                    } else if (doc) {
                        return result(doc)
                    } else {
                        return result('Something went wrong while saving');
                    }
                })
            });`

When the document is saved, the visitors array looks like this:

`"visitors" : []`

But after the code above runs 'successfully', visitors becomes (on mLab):

`"visitors": {
        "_id": {
            "$oid": "58f9a97daff2370011c5de2c"
        }
    }`

Any tips on why this might be happening?  If you need the code for how i obtain the model reference to the collection let me know. Many thanks.
