### ISSUE TITLE
11000 E11000 duplicate key error index: dbName.users.$_id_ dup key: { : ObjectId('5469eb08370fea375383e2d3')}

### ISSUE THREAD

**Issue by MrDHat** [LearnBoost/mongoose#2471]
I am trying to save an an array of objects into a db using `db.collection.insert` but I am getting this error:
```
{"code":11000,"index":93,"errmsg":"insertDocument :: caused by :: 11000 E11000 duplicate key error index: dbName.users.$_id_ dup key: { : ObjectId('5469eb08370fea375383e2d3') }
```
I've tried dropping the database and reinserting but of no use. Also, no document with such id is present in the collection earlier.

**Comment by vkarpov15** [comment]
No response for a while. Re-open if its still an issue.

**Comment by saprative** [comment]
having the same kind of problem

**Comment by dhanabalt** [comment]
me too having the same problem

**Comment by vkarpov15** [comment]
Please provide more context @saprative @dhanabalt

**Comment by saprative** [comment]
it was a mongo connection error i have solved it

**Comment by agamanyuk** [comment]
I have the same error.
After successful inserting of 1.8M of documents I received  E11000 duplicate key error index: $_id_ dup key.

I'm inserting documents without assigning _id. The batch size is 50k,  avgObjSize is 250.
I'm usuing a sharded cluster with replica set and MongoDB.Driver dotnet driver.Bulk write operations can be either unordered.

What am I doing wrong? Should I set the ID's on client level before calling insert? Should I decrease the size of the batch? Any ideas?

**Comment by vkarpov15** [comment]
If you're using the .NET driver, why are you asking this question on the mongoose github?

**Comment by agamanyuk** [comment]
I didn't notice this thread is specific to mongoose, I thought it's a mongodb one.... Ok, that's enough for today, going home...

**Comment by saprative** [comment]
@agamanyuk Yes it a mongoose specific error.  I have faced that while working .

**Comment by vkarpov15** [comment]
@agamanyuk wish I could help, but this is the github for a mongodb node.js ODM. I haven't touched .NET since 2007, so I wouldn't be the right person to ask because I don't even have a setup capable of running .NET code.

**Comment by vkarpov15** [comment]
You might want to take a look at https://github.com/mongodb/mongo-csharp-driver and https://jira.mongodb.org/browse/CSHARP

**Comment by RamprasadAkella** [comment]
Is this resolved ? getting same error as mentioned by MrDHat @vkarpov15  Please let me know.

**Comment by vkarpov15** [comment]
Provide code samples please, otherwise not much I can do to help.

**Comment by river4321** [comment]
In python, once you inserted, the "contacts" has a "ObjectID" key. So , delete it when next loop

**Comment by vervald** [comment]
```
var aladdinId;
    //добавление аладина
    db.collection('Aladdins').insertOne({
      "hash" :  totalAmounts.terminals,
      "public_key_1" :  totalAmounts.terminals,
      "test" : true,
      "created" : 1446296623,
      "updated" : 1446296623,
      "terminal": {"uid": ObjectId(terminalUid)}
      }, function(err, result) {
        assert.equal(err, null);
        aladdinId = result.insertedId;
        var hostId;
        //добавление хоста
        db.collection('Hosts').insertOne({
          "type1" : "ssh",
          "port_counter" : 7108,
          "host": "update1.fet.ru"
          }, function(err, result) {
            assert.equal(err, null);
            hostId = result.insertedId;
            //обновление терминала
            db.collection('Terminals').update(
                {'_id': terminalUid},
                {'$set':
                  {
                    'aladdin':{'uid': ObjectId(aladdinId), 'hash':  "887209212797234849"},
                    'host': {'host': 'update1.fet.ru', 'uid': ObjectId(hostId), 'port': 7108}
                  }
                }, function(err, result) {
                  callback(null, db, totalAmounts, insertedClient);
                }
            );
        });
    });
  });
};
```

` An error occurred while running the tests:
AssertionError: {"name":"MongoError","message":"E11000 duplicate key error collection: loto_test_soper.Aladdins index: public_key_1 dup key: { : == null
    at /home/severin/projects/NightwatchTests/js/database/insertions.js:436:16
    at /home/severin/projects/NightwatchTests/node_modules/mongodb/lib/collection.js:404:32
    at handleCallback (/home/severin/projects/NightwatchTests/node_modules/mongodb/lib/utils.js:96:12)
    at /home/severin/projects/NightwatchTests/node_modules/mongodb/lib/collection.js:685:42
    at commandCallback (/home/severin/projects/NightwatchTests/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:936:9)
    at Callbacks.emit (/home/severin/projects/NightwatchTests/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:116:3)
    at null.messageHandler (/home/severin/projects/NightwatchTests/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:282:23)
    at Socket.<anonymous> (/home/severin/projects/NightwatchTests/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:273:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
`

**Comment by vkarpov15** [comment]
@vervald you have a unique index on `public_key_1` and you're inserting two aladdins with `public_key_1` = null. Make sure you're cleaning up your db between tests properly, or if this is by design you might want to look at [sparse indexes](https://docs.mongodb.org/manual/core/index-sparse/)

**Comment by hosein** [comment]
I too am having this problem.

- Target collection has no explicit unique indexes (aside from the auto-create _id).

- I am inserting an array of entries, ranging from 2-1000 (I see failures mostly the 20-50 range, they rarely go above 100 at a clip).

- _id is NOT being created prior to insert (I am not migrating data from one schema to another)

- This happens on both a freshly dropped collection or an existing one

db.MyCollection.getIndexes() yields:
```
> db.MyCollection.getIndexes()
[
	{
		"v" : 1,
		"name" : "_id_",
		"key" : {
			"_id" : 1
		},
		"ns" : "myDb.MyCollection"
	},
	{
		"v" : 1,
		"name" : "myField",
		"key" : {
			"myField" : 1
		},
		"ns" : "myDb.MyCollection",
		"background" : true,
		"safe" : null
	},
	{
		"v" : 1,
		"name" : "myFieldOtherField",
		"key" : {
			"myFieldOtherField" : 1
		},
		"ns" : "myDb.MyCollection",
		"background" : true,
		"safe" : null
	}
]
```

Code is:
```
if (myArray.length > 0) {
        models.myCollection.collection.insert(myArray, function(err) {
            if (err) {
                logger.error("Error saving your array " + err)                     
            }                                    
        });    
    }
    else {
        logger.info('Sanitizing code is fun!')
    }

```

Schema is 18 fields, mostly Ints with a few Strings, one String can be large, but usually is under 20 characters.  Typical size of each array element is roughly 500B according to http://bytesizematters.com/.

Let me know if you need more information.

**Comment by vkarpov15** [comment]
Where is the looping code? How is `myArray` generated?

**Comment by hosein** [comment]
@vkarpov15 
The data is a raw .csv input that is JSON.stringify() before input into Redis, then JSON.parse() after it's pulled back out for insertion to Mongo.  Each line essentially becomes an object in the myArray.

It is possible that some of the date fields could contain the same exact time, but other than that no other collisions, and definitely no _id field.

I can provide a sample of the data if you like, just let me know.

**Comment by gcr-nist** [comment]
I am having a similar problem and would like to weigh in if I may.
I am using the java and Spring.  As a test, I query an object by id, then try to save the same object without updating anything.  I get a duplicate key exception when I do this.  

A bit of code:
		Datatype sut = datatypeService.findById("569eac0fd4c623dc6550ecae");  // Succeeds
		datatypeService.save(sut);  // Fails with duplicate key.  )Save calls update.)

Why?  Repeat the above with other classes and they work.  How can I trouble shoot this?  I don't see how to break it down and isolate the problem.

**Comment by vkarpov15** [comment]
@hosein sample data and sample code will help a lot. Code always sounds right when describing it in prose.

@gcr-nist this is a JS module, definitely not the right place to be asking Java questions. I've never used spring and haven't written any non react native java in years, I'm afraid I wouldn't be much help

**Comment by iruimeng** [comment]
in php foreach，next loop $data has been modified. add index '_id'. unset it.
php:
unset($data['_id']);

python

if '_id' in ddict:
    del ddict['_id']

**Comment by InventSrinath** [comment]
I have this same issue after inserting 800K records, I am working with MLab (mongodb) and NodeJS which run as a job. 

Code used to Insert: BulkInsert is the array of object to be inserted.
function bulkInsert(collectionName, bulkInsert, callback){
    console.log(bulkInsert ? bulkInsert[0] : bulkInsert);  
    mongodb.MongoClient.connect(dataBaseurl, function (err, database) {
        if (err) {
            console.log(err);
            process.exit(1);
        }        
        var docCollection = []        
        // Save database object from the callback for reuse.   
        console.log("Database connection ready for bulk Insert");
        database.collection(collectionName).insertMany(bulkInsert, function(err, result) {
             database.close();
             callback(err, result);             
        });      
    });    
}  
Error:
Bulk Insert failes - WriteError({"code":11000,"index":267,"errmsg":"E11000 duplicate key error index:
coinspredictions.Coins.$_id_ dup key: { : ObjectId('595936942325c71968b1ec77') }","op":{"BTC":0.000002
35,"USD":0.005904,"EUR":0.005114,"currency":"UTC","up":1,"down":0,"created":"2017-07-02T18:08:19.244Z"
,"batch":250,"dorm":1,"_id":"595936942325c71968b1ec77"}})

Thanks in Advance.

**Comment by hosein** [comment]
@InventSrinath Try removing the _id, that was my issue.  You'll find that simply deleting does not always work, you may have to .toObject() it as well.

**Comment by vkarpov15** [comment]
@InventSrinath it doesn't look like you're actually using mongoose anywhere, the mongodb driver is a separate project

**Comment by TheeeeeFrechman** [comment]
so,the issue‘s answer is that delete the _id(objectId) befor insert a message?

**Comment by vkarpov15** [comment]
@TheeeeeFrechman yes. Or do a shallow clone before writing like `db.collection('coll').insertOne(Object.assign({}, doc))`

**Comment by ShaguftaMethwani** [comment]
I have a piece of code, as following and have the same problem in Java. `coll` is the collection where I need to insert data. I was hoping mongodb would automatically generate the ids so putting the same data (in a for loop) wouldn't matter but I get this same error being discussed in this thread. Any idea what should I do?
```
         //   String json1 = XML.toJSONObject(xml_text).toString();
         //   DBObject dbo = (DBObject) com.mongodb.util.JSON.parse(json1);
        //    List<DBObject> list = new ArrayList<>();
        //    list.add(dbo);
            
            for (int i = 0; i < 5000; i++) {
                coll.insert(list);
            }
```

**Comment by vkarpov15** [comment]
I'd ask this on the [MongoDB Java driver's JIRA page](https://jira.mongodb.org/projects/JAVA/issues), we don't really know java here...

**Comment by kevintbradbury** [comment]
Also check your key names, in my case I tried: 

1. dropping the collection
2. dropping the whole database
3. removing {index: {unique: true}}

and finally found it was referencing an older key name, where username was all lowercase

**Comment by skinnn** [comment]
I fixed the E11000 duplicate key error indexes with: new Schema({..}, { **autoIndex: false** });

When your application starts up, Mongoose automatically calls createIndex for each defined index in your schema. Mongoose will call createIndex for each index sequentially, and emit an 'index' event on the model when all the createIndex calls succeeded or when there was an error. While nice for development, it is recommended this behavior be disabled in production since index creation can cause a significant performance impact. Disable the behavior by setting the autoIndex option of your schema to false, or globally on the connection by setting the option autoIndex to false.

  mongoose.connect('mongodb://user:pass@localhost:port/database', { autoIndex: false });
  // or
  mongoose.createConnection('mongodb://user:pass@localhost:port/database', { autoIndex: false });
  // or
  animalSchema.set('autoIndex', false);
  // or
  new Schema({..}, { autoIndex: false });

**Comment by chen-i** [comment]
I solved the problem by referring to http://xiaoweiliu.cn/2017/06/21/pymongo-errors-DuplicateKeyError-E11000-duplicate-key-error/.

**Comment by githubjiangweiling** [comment]
Hi,
I have a problem about using Mongo to set up a local Blast2GO GO Database.
I'm trying to set up Blast2GO based on Blast2eGO CLI User Manual on Linux 64 bit(Ubuntu 16.04).After I finished downloading Mongo 3.6.4, I ran the command "mongorestore --host 192.168.1.240 --db go_db --collection 2017.12 --gzip --archive=2017.12.gz". But the screen showed “Failed: error connecting to db server: no reachable servers” . Then I viewed the file of /etc/mongod.conf and modifed the hostIP to 127.0.0.1:27017. Still an error occurred despite its ability to run. Some of the screen contents are as follows：
...
- E11000 duplicate key error collection: go_db.2017.12 index: _id_ dup key: { : ObjectId('5a54fe94dc0e820127648760') }
- E11000 duplicate key error collection: go_db.2017.12 index: _id_ dup key: { : ObjectId('5a54fe94dc0e820127648763') }
2018-04-21T22:09:20.009+0800	error: E11000 duplicate key error collection: go_db.2017.12 index: _id_ dup key: { : ObjectId('5a54fe94dc0e82012764855f') }
2018-04-21T22:09:20.009+0800	error: E11000 duplicate key error collection: go_db.2017.12 index: _id_ dup key: { : ObjectId('5a54fe94dc0e8201276483d6') }
2018-04-21T22:09:20.009+0800	go_db.2017.12  53.7GB
2018-04-21T22:09:20.009+0800	restoring indexes for collection go_db.2017.12 from metadata
2018-04-21T22:09:20.009+0800	finished restoring go_db.2017.12 (70701468 documents)
2018-04-21T22:09:20.009+0800	done
I still don't know how to solve this problem after I read some literature.Please give me some advice.Thanks a lot!

**Comment by mayeaux** [comment]
Thanks @skinnn

**Comment by grantcarthew** [comment]
Thank you so much @skinnn. I have been working on a database reset script for the last day and nothing I tried was working. Randomly got the `dup key` issue. You just saved me more time wasted on this issue.

**Comment by wycliffepeart** [comment]
Forcing server object id to true might help to resolved this problem 

{
    forceServerObjectId: true
}

**Comment by grantcarthew** [comment]
Hi @wycliffepeart. Thanks for the feedback. I have read up what I can about the `forceServerObjectId` option and don't think this would help. I am importing some JSON files that have a fixed _id.

It does seem very strange. I am dropping the database (using await) and then initializing the models with `autoIndex` set to false. Then I am looping through the JSON files saving the new models.  Even with a timeout delay it causes a `dup key` every now and then. You would think dropping the database would ensure the collections and indexes got removed.

Thanks again.

**Comment by vkarpov15** [comment]
@grantcarthew because MongoDB collections have a unique index on `_id` by default, and you can't get rid of that index. Mongoose doesn't actually build that index.

**Comment by grantcarthew** [comment]
Ok, thanks @vkarpov15. So if you have a fixed set of json documents you want to import with a fixed `_id` of 001 and 002 etc. How do you delete the database/collection/document in a script and immediately re-create it?. Nothing I have tried works 100% of the time. This is mostly for testing purposes. 

Thanks for your time. Sorry to be a bother. I am working around it at the moment.

I just had an idea. Maybe I could try the `Model.findOneAneUpdate()` method to overwrite the documents rather than `Document.save()`.

**Comment by vkarpov15** [comment]
@grantcarthew to delete a collection use [`dropCollection()`](http://mongoosejs.com/docs/api.html#connection_Connection-dropCollection) and to create the collection again use [`createCollection()`](http://mongoosejs.com/docs/api.html#connection_Connection-createCollection), although I'm not sure why you would want to do that. Even if you delete the collection and recreate it, there's no way to write multiple docs with the same `_id`.

You probably want to do [`findOneAndUpdate()` with the `upsert` option set](http://mongoosejs.com/docs/api.html#findbyidandupdate_findByIdAndUpdate)

**Comment by grantcarthew** [comment]
@vkarpov15 thanks mate. I've run the script a few times now and it is not causing the error. Maybe a reboot fixed it. I'll see if it happens again. Note: I was not trying to add duplicate ids, I was trying to drop everything and add back the same set of ids. All good for now thanks.

**Comment by SimonWang00** [comment]
I also used Python to encounter _id repeated problems and I did not manually add data in the collection.

**Comment by grantcarthew** [comment]
Sorry @SimonWang00 I didn't find a solution, I have moved to using JSON Schemas and the MongoDB driver. Mongoose was more APIs to learn with legacy version responses on StackOverflow.

**Comment by vkarpov15** [comment]
Read [Debug E11000 Errors in Mongoose](https://masteringjs.io/tutorials/mongoose/e11000-duplicate-key)
