### ISSUE TITLE
unique, sparse index not working on subdocuments

### ISSUE THREAD

**Issue by mephju** [LearnBoost/mongoose#2476]
Hi,
unique, sparse indices don't work for subdocuments.

```javascript
var orderSchema = new mongoose.Schema({
  orderNum: { 
			type: Number, 
			default: 1001,
			required: true, 
			unique: true, 
			sparse: true
  },
})

var userSchema = new mongoose.Schema({
  orders:[orderSchema]
})
```

As I understand it should not be possible to insert multiple orders with orderNum: 1001. And in fact that is true if a unique sparse index is defined on the parent. But on subdocs it doesn't work!

What's going on?

**Comment by vkarpov15** [comment]
So I think you're running in to the classic gotcha with mongodb unique indexes. A unique index [prevents multiple documents from having the same value for the indexed key, but from multiple subdocs in an array having the same value for the indexed key](http://docs.mongodb.org/manual/core/index-unique/#unique-constraint-across-separate-documents). For instance, with the above schema, a single User can have multiple orders with `orderNum = 1001`, but only one User can have an order with `orderNum = 1001`. The below code demos this:

```javascript
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

var orderSchema = new mongoose.Schema({
  orderNum: { 
            type: Number, 
            default: 1001,
            required: true, 
            unique: true, 
            sparse: true
  },
});

var userSchema = new mongoose.Schema({
  orders:[orderSchema]
});

var User = mongoose.model('users', userSchema, 'gh-2473');

User.remove({}, function() {
  var u = new User({ orders: [{}] });
  console.log('Initial: ' + JSON.stringify(u));
  u.save(function(err, u) {
    console.log('err: ' + err);
    u.orders.push({});
    console.log('After first save: ' + JSON.stringify(u));
    // This save will succeed because there's only 1 doc in collection
    u.save(function(err, u) {
      console.log('err: ' + err);
      console.log('After 2nd save: ' + JSON.stringify(u));
      var u2 = new User({ orders: [{}] });
      // This will throw an index error, because both u and u2 have an order with orderNum = 1001
      u2.save(function(err) {
        console.log('Error occurred! ' + err);
      });
    });
  });
});
```

**Comment by patrickcorrigan** [comment]
What's is the solution to this problem? Is it to reference documents instead of embedding them?

**Comment by vkarpov15** [comment]
@patrickcorrigan there's a few workarounds:

1) Enforce uniqueness of `orderNum` in your app. In order to make this work consistently, don't use `$push`, just overwrite the entire array with each save.
2) Have a separate array of `orderNums` (as numbers) and use [`$addToSet`](https://docs.mongodb.com/manual/reference/operator/update/addToSet/)
3) References rather than embedding

Right answer depends on your use case. If your array is pretty small I'd recommend going with 1, if your array is large and expected to grow I'd recommend 3, if your array is big but you really need to embed for some reason then go with 2.

**Comment by keith24** [comment]
> For instance, with the above schema, a single User can have multiple orders with `orderNum = 1001`, but only one User can have an order with `orderNum = 1001`.

This is the exact opposite of how I imagine subdocuments working!  I guess it's mongo's fault, and not mongoose's.  I'll have to write them an angry letter... :laughing: 

I'm not using `default`, so it doesn't seem like the second and third workarounds apply to my case, but I do want unique subdocs per parent (not globally).  I guess there's no way around it: I have to remove `unique` and write my own validation code.  This is a bit of a drag, considering the mongoose ethos: 

> Let's face it, writing MongoDB validation, casting and business logic boilerplate is a drag. That's why we wrote Mongoose.
> --[the homepage](http://mongoosejs.com/index.html)

If it is at all possible for mongoose to perform this sort of subdoc validation with `unique` (or some other option), despite its origins in "MongoDB [Bizarro World](https://en.wikipedia.org/wiki/Bizarro_World)", I hereby cast my vote for that feature request.

**Comment by vkarpov15** [comment]
It is pretty annoying, but it's really difficult to do that right in general without help from the mongodb server. The only way I can think of that doesn't have a race condition is `findOneAndUpdate()` with that particular field combined with a unique index:

```javascript
// assume unique index on `orders.orderNum`
Order.findOneAndUpdate({ _id: order._id, 'orders.orderNum': { $ne: 1001 } }, { $push: { orders: { orderNum: 1001 } } });
```

But that wouldn't work well within mongoose's `save()` API, we'd need to execute multiple queries.
