### ISSUE TITLE
Is it possible create string subdocument array

### ISSUE THREAD

**Issue by Mirodil** [LearnBoost/mongoose#2488]
For example:
```javascript
var ItemSchema = new Schema({    
    /**
     * item title
     * */
    title: {
        type: String,
        trim: true,
        required: [true, 'This title is required']
    },    
    /**
     * item tags
     * */
    tags: [
        {
			type: String,
			trim: true,
			lowercase: true
		}
    ]
});
```

in the above example `lowercase: true` for `tags` string array field doesn't working at all.

is it possible create such type of field?

**Comment by vkarpov15** [comment]
So this is fixed in 4.0.0-rc1, see #1277, #661, etc. Will not be fixed in 3.8.x: its an additive feature. For a workaround, [check out this gist](https://gist.github.com/aheckmann/1512125)
