### ISSUE TITLE
update with $push and $addToSet now calls Schema.options.toObject.transform twice on Array objects

### ISSUE THREAD

**Issue by jlchereau** [LearnBoost/mongoose#2537]
This is a follow up to https://github.com/LearnBoost/mongoose/issues/2301

The workaround described (in fact a similar approach where I set doc.doNotTransform = true and then test it) now fails because mongoose v3.8.20 calls Schema.options.toObject.transform twice on each subdocument added to an array. It was still working with mongoose v3.8.19.

In version 3.8.19 Model.update (see model.js line 1626) was:
```js
Model.update = function update (conditions, doc, options, callback) {
  var mq = new Query({}, {}, this, this.collection);
  return mq.update(conditions, doc, options, callback);
};
```

In version 3.8.20 Model.update (see model.js line 1635) is:
```js
Model.update = function update (conditions, doc, options, callback) {
  var mq = new Query({}, {}, this, this.collection);
  // gh-2406
  // make local deep copy of non-function parameters
  conditions = utils.clone(conditions);
  doc = utils.clone(doc);
  options = typeof options === 'function' ? options : utils.clone(options);

  return mq.update(conditions, doc, options, callback);
};
```

In v3.8.20 Schema.options.toObject.transform  is called:
- Once in *utils.clone* (line 1635)
- Once *mq.update* (ine 1638) as in previous versions

Besides, this is also inefficient.

**Comment by PaulMougel** [comment]
Hi! Any news about this? We're using 3.8.22 and are still experiencing the bug referenced in #2301.

How can we help?

**Comment by vkarpov15** [comment]
You're going to have to help me repro this. The below code only executes the transform once in 3.8.22 and seems to perform the right update.

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var db = mongoose.createConnection('mongodb://localhost/tests');

var versionSchema = new mongoose.Schema({
    published           : { type: Date }
});

versionSchema.options = {
  toObject: {
    transform: function(doc, ret) {
      console.log('transform');
    }
  }
};

var summarySchema = new mongoose.Schema({
    versions            : { type: [versionSchema], default: [], select: false }
});
var Model = db.model('Summary', summarySchema);

var m = new Model();
m.versions.push({ published: new Date() });
console.log(JSON.stringify(m));

m.save(function(err, m) {
  console.log(err + ' :: ' + JSON.stringify(m));
  Model.update({ _id: m._id }, { $push: { versions: { _id: mongoose.Types.ObjectId() } } }, function(err, affected) {
    console.log(err + ' :: ' + affected);
    Model.findOne({ _id: m._id }, function(err, doc) {
      console.log('err: ' + err + ', doc: ' + JSON.stringify(doc));
    });
  });
});
```

**Comment by PaulMougel** [comment]
Mac Os Yosemite 10.10.1, mongoose@3.8.22, node v0.10.35, mongod v2.6.7
```
{"_id":"54d1d155ddb836577806ec54","versions":[{"published":"2015-02-04T07:59:17.033Z","_id":"54d1d155ddb836577806ec55"}]}
null :: {"__v":0,"_id":"54d1d155ddb836577806ec54","versions":[{"published":"2015-02-04T07:59:17.033Z","_id":"54d1d155ddb836577806ec55"}]}
transform
null :: 1
err: null, doc: {"_id":"54d1d155ddb836577806ec54","__v":0}
```

`transform` seems to be called once, but (unless I'm mistaken) the update is not performed correctly.

**Comment by vkarpov15** [comment]
Good catch

**Comment by vkarpov15** [comment]
Actually @PaulMougel that's just due to the `select: false` in the schema, so `versions` not appearing is expected. Output without `select: false` is:

```
{"_id":"54d2a09482a2f9e32bf8b1d4","versions":[{"published":"2015-02-04T22:43:32.542Z","_id":"54d2a09482a2f9e32bf8b1d5"}]}
null :: {"__v":0,"_id":"54d2a09482a2f9e32bf8b1d4","versions":[{"published":"2015-02-04T22:43:32.542Z","_id":"54d2a09482a2f9e32bf8b1d5"}]}
transform
null :: 1
err: null, doc: {"_id":"54d2a09482a2f9e32bf8b1d4","__v":0,"versions":[{"published":"2015-02-04T22:43:32.542Z","_id":"54d2a09482a2f9e32bf8b1d5"},{"_id":"54d2a09482a2f9e32bf8b1d6"}]}
```

**Comment by PaulMougel** [comment]
Indeed.
I can't exactly reproduce the bug I was experiencing a couple of days ago… maybe it wasn't related to mongoose.

**Comment by jlchereau** [comment]
I am still experiencing the issue with version 3.8.22:

![image](https://cloud.githubusercontent.com/assets/2556751/6076248/a8e00e74-add8-11e4-8b06-5552dc4d7078.png)
https://github.com/Memba/Kidoju-Server/blob/master/api/db/userSchema.js#L366

![image](https://cloud.githubusercontent.com/assets/2556751/6076268/0841d74e-add9-11e4-8b1b-f49adfff0fa8.png)
https://github.com/Memba/Kidoju-Server/blob/master/api/db/userSchema.js#L62

The stack trace shows that first transform is executed in clone in util.js: https://github.com/LearnBoost/mongoose/blob/master/lib/utils.js#L227
called from update in model.js: https://github.com/LearnBoost/mongoose/blob/master/lib/model.js#L1743

![image](https://cloud.githubusercontent.com/assets/2556751/6076289/636c7246-add9-11e4-8a31-41ae01691b6f.png)

and the second transform is executed in castForQuery in array.js:
https://github.com/LearnBoost/mongoose/blob/master/lib/schema/array.js#L209
also called from update in model.js
https://github.com/LearnBoost/mongoose/blob/master/lib/model.js#L1746

![image](https://cloud.githubusercontent.com/assets/2556751/6076332/0a46f32a-adda-11e4-9083-01bbe99f70a9.png)

**Comment by vkarpov15** [comment]
You're right, that clone() call was redundant, its removed. The reason why I couldn't repro was that you were using `DocumentArray.create()` to create a new favorite.

**Comment by vkarpov15** [comment]
Also, FWIW, "clone a large server project and run all the tests" is not a great way to help me repro. At least tell me which test to run :)

**Comment by jlchereau** [comment]
I am really sorry you feel that way.

I had 2 options:

1. respond quickly to your request with I had in store, considering cloning a repository and running npm install takes less than 5 minutes;
2. wait a couple of weeks, maybe more, until I could spend a couple of hours building a repro test case.

I made a call. With the right tools, the size of the project is irrelevant. It is all in the location of the breakpoint, which you should have hit in a matter of seconds after setup. Once on the breakboint, the stack gives you the test to run.

**Comment by vkarpov15** [comment]
I don't really use debuggers in any language, so I'd have to actually learn how to use node inspector for that to work. On the positive side, pointing out the relevant lines of code was very useful. Finding the `.create()` made reproing pretty easy. Thanks for pointing this out.
