### ISSUE TITLE
Upgrade to node-mongodb-native 2.0

### ISSUE THREAD

**Issue by vkarpov15** [LearnBoost/mongoose#2552]

**Comment by memelet** [comment]
Seems driver-upgrade is in sync with master/(4.x?), is that correct?

**Comment by memelet** [comment]
Also, is there way to see formatted docs for the driver-upgrade branch (or any specific branch for that matter)?

**Comment by vkarpov15** [comment]
@memelet nope, I see that branch as 11 commits ahead and 8 commits behind master atm.

And the doc changes for the driver upgrade branch will be minimal (as a matter of fact, there are none right now unfortunately). To see the generated docs, you'll need to run `make gendocs` yourself unfortunately.
