### ISSUE TITLE
Model.Update $push does not insert past 5 items into an array subdocument

### ISSUE THREAD

**Issue by balmasi** [LearnBoost/mongoose#2555]
Given the Quote Model schema exerpt:
```
  messages:[
    {
      from: {
        type: Schema.Types.ObjectId,
        ref: 'User'
      },
      message: String
    }
  ],
```
and query/update 

```
  var qId = req.params.id;
  var message = req.body
  Quote.update(qId, {
    $push: {
      messages: message
    }
  }, function(err, numAffected, rawResponse) {
    if (err) { return handleError(res, err); }
    if(!numAffected) { return res.send(404); }
    return res.json(201, message);
  })
```
numAffected and rawResponse both indicate a successful insert but it doesn't insert more than 5 items into the array (as in,first 5 inserts are fine, then just seems to throw it away even though it indicates success...)

```
  var qId = req.params.id;
  var message = req.body
  Quote.findByIdAndUpdate(qId, {
    $push: {
      messages: message
    }
  }, function(err, quote) {
    if (err) { return handleError(res, err); }
    if(!quote) { return res.send(404); }
    return res.json(201, message);
  })
```
This is supposed to be the same query, but this works for some reason. Anyone else experience this?

**Comment by vkarpov15** [comment]
@jtmarmon is right, the first case has a malformed query. Does fixing that fix your issue?

**Comment by balmasi** [comment]
Oh damn, totally my bad... Still makes me wonder why such a query is accepted though, and why it worked for the first 5 queries 8|
