### ISSUE TITLE
pre validate hook not firing on new model

### ISSUE THREAD

**Issue by gmaniac** [LearnBoost/mongoose#2557]
I am trying to create a model then create another model and save the reference to the original model using mongoose. I have been looking through mongoose's documentation on middleware and their hooks, but some of those don't seem to fire.

This answer on stackoverflow tells me why my init hook would not fire [HERE](http://stackoverflow.com/a/12268608/1146562), `pre` and `post` `init` only fire when loading a pre existing model from the db. So I read that `validate` would run on the creation of a new model. In knowing that I switched from `pre` `init` to `pre` `validate`.

Here is the code for what I am trying to do:

```javascript
GroupSchema.pre('validate', function (next, data) {
    console.log("inside pre validate");
    if (data.location) {
        location = new Location(data.location);
        data.location = location._id;
        location.save(function (err) {
            if (err) handleError(err);
        });
    }

    next();
})
```
I know I can't use this because the document is not populated with data yet. So that is why I have data, but this still does not seem to work, oh I got which parameters I am supposed to pass in from this [answer](http://stackoverflow.com/a/14694211/1146562) on stackoverflow as well.

using:
`"mongoose": "~3.8.20",`

**Comment by gmaniac** [comment]
Thank you for getting back to me on this.

So is there any way to do this with a hook?

save a model -> get generated ObjectId -> store on original Object

Reason I was trying to add this to a pre hook is so that I could have this code in one spot and it automatically would handle this when newing up a model.

**Comment by vkarpov15** [comment]
Why don't you just call `toObject()` on the model after save? Or you can use a pre save hook that checks `this.isNew`, which is true if the document that you're saving is a new document?

**Comment by gmaniac** [comment]
I am going with this answer on stackoverflow. Thank you for your help!

http://stackoverflow.com/a/27751161/1146562
