### ISSUE TITLE
Populate not always working

### ISSUE THREAD

**Issue by alexislg2** [LearnBoost/mongoose#2559]
Hey, I'm experiencing a very strange behaviour with the populate function. It is working 99% of the times but sometimes not:
```player.populate({path: "game.shops", select: "location2d revenue", model: "Poi"}, function(err, player){
                        if (err) throw err;
                        var shops = player.game.shops;
});```

In 99% percent of the cases the variables `shops` contains an array of the shops owned by the player but sometimes it gives me only their Mongoose id (` ["5450c4aaf5844bd32a984e1b","5450c4aaf5844bd32a98581f"]`)

Any idea why this strange behaviour?

I'm using mongoose 3.8.17 with mongoDB 1.4.9

**Comment by vkarpov15** [comment]
What do the underlying documents look like and what do your schemas look like? My first guess would be that some documents in the db are saved with string `_id` but your schema expects the `_id` to be an ObjectId.

**Comment by alexislg2** [comment]
Thanks for your answer.
I'm sorry I think it was my mistake. I had an asynchronous issue in my code (callback called twice in a subfunction). I guess that was the cause of my issue, not mongoose.
Thanks for your help and sorry for the annoyance

**Comment by GaddMaster** [comment]
I am experiencing this issue also. Some of my articles' tags are not populated, some are. Sometimes a refresh and they are. investigating now. Will share and findings.
