### ISSUE TITLE
parseError occured when querying result is big

### ISSUE THREAD

**Issue by YoleYu** [LearnBoost/mongoose#2564]
```javascript
Player.find({ season: 14}).sort({playerId: 1}).exec(function(err, dbPlayers) 
```
parseError occured when querying result is big

while I change the query condition to limit the result size
```javascript
Player.find({ season: 14, xx : {$gt :80}}).sort({playerId: 1}).exec(function(err, dbPlayers) 
```
No error will come.

I am not sure if it's a bug or I should using some other way to query big result

**Comment by vkarpov15** [comment]
Could this be an instance of [this issue](http://stackoverflow.com/questions/21767673/mongodb-parseerror-when-using-limit-and-sort)? According to [MongoDB's docs on the sort operation](http://docs.mongodb.org/manual/tutorial/sort-results-with-indexes/), "sort operations that do *not* use an index will abort when they use 32 megabytes of memory." Do you have an index on season and playerId?

**Comment by YoleYu** [comment]
@vkarpov15  I haven't add index on these fields, my mistake, but if the error log has more detail infomation, that will be easier for troubleshooting. Thanks.
