### ISSUE TITLE
Support tokumx database instead of just mongodb

### ISSUE THREAD

**Issue by bitplanets** [LearnBoost/mongoose#2565]
TokuMX is an open source, high-performance distribution of MongoDB that dramatically improves performance and operational efficiency compared to basic MongoDB. **TokuMX is a drop-in replacement for MongoDB and reduces costs associated with development, scaling, and optimization**

 - [What is](http://www.tokutek.com/tokumx-for-mongodb/)
 - http://www.severalnines.com/blog/nosql-battle-east-coast-benchmarking-mongodb-vs-tokumx-cluster

**Comment by vkarpov15** [comment]
I hear good things about TokuMX, but that's unlikely to happen any time soon: supporting multiple versions of one database in a clean way is tricky enough, supporting an entirely separate database will probably lead to a lot of code bloat. You're more than welcome to write your own using mongoose as a starting point though :)

![Multi-database ORM](https://pbs.twimg.com/media/B3NF0SXCYAIVbrA.jpg)
