### ISSUE TITLE
Validation can block $unset of path

### ISSUE THREAD

**Issue by DrDanRyan** [LearnBoost/mongoose#2566]
I recently discovered that you can assign a value of `undefined` to a path to perform an `$unset` operation. However, if the path has validation, the validation tests the `undefined` value during a call to `save` which is not necessarily desired. For instance,

```javascript
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/mongoose_test');

var personSchema = new mongoose.Schema({
  name: String,
  age: {type: Number, min:0}
});

Person = mongoose.model('Person', personSchema);

// Database contains single person:
// {name:'Phil', age:30}

Person.findOne({name:'Phil'}, function (err, doc) {
  doc.age = undefined; // $unset the age path
  doc.save( function (err) {
    if (err) { console.log(err); }
    mongoose.disconnect();
  });
});
```

fails with the error
```javascript
{ [ValidationError: Validation failed]
  message: 'Validation failed',
  name: 'ValidationError',
  errors: 
   { age: 
      { [ValidatorError: Path `age` () is less than minimum allowed value (0).]
        message: 'Path `age` () is less than minimum allowed value (0).',
        name: 'ValidatorError',
        path: 'age',
        type: 'min',
        value: undefined } } }
```

This doesn't seem like the right behavior, since it is valid under the schema to `save` a `Person` with no age value specified. Note, that it also fails for `max` validators; I haven't played with other validation types.

**Comment by vkarpov15** [comment]
This was fixed in the unstable branches, see #1594. Fix will be released soon :)
