### ISSUE TITLE
Asynchronous getters/setters

### ISSUE THREAD

**Issue by njoyard** [LearnBoost/mongoose#2571]
Hello,

Is there a way to implement asynchronous getters with mongoose ?

I'm having a hard time populating DBrefs in a tree-like structure (where documents contain a plain tree of arbitrary depth, where some nodes have a DBref as a property), and I figured out I could use asynchronous getters (if they existed) to manually populate those without having to call `.populate()` with all possible nested DBref paths...

**Comment by vkarpov15** [comment]
Nope, no way to do async getters/setters. That's just the nature of ECMAScript 5. Mongoose won't be adding support for this any time soon, I'd recommend you just implement this with a helper function.
