### ISSUE TITLE
Document#populated returns all ids instead of matching populate options

### ISSUE THREAD

**Issue by Kuzirashi** [LearnBoost/mongoose#2573]
Document#populated returns all ids instead of only these matching arguments passed to .populate(). Example:
~~~~ CoffeeScript
Profile.findById req.params.profile_id
      .populate
        path: 'receivedNotifications'
        select: '_id'
        match: { read: false }
        options:
          sort: { date: -1 }

      .exec (err, profile) ->
        if err or not profile
          ErrorController.handleError err, profile, res
                  profile.entriesLength = count
                  console.log profile.receivedNotifications
                  console.log 'vs'
                  console.log profile.populated 'receivedNotifications'
~~~~
Results in:
~~~~
[{"id":"54a5c4b3b0d89cb15215dbe7"},{"id":"54a588e8e7f1123165577996"}]
vs
[ 54a588e8e7f1123165577996,
  54a5c4b3b0d89cb15215dbe7,
  54a5c4e0b0d89cb15215dbe9 ]
~~~~
`profile.populated('receivedNotifications')` returns records that do not match: `match: { read: false }`.

**Comment by vkarpov15** [comment]
Expected behavior, see [populated API docs](http://mongoosejs.com/docs/api.html#document_Document-populated). Will return the _id's used for the query used to populate. Since mongoose doesn't know what documents match the query beforehand, it'll pass all the _ids to the underlying query.
