### ISSUE TITLE
Unique doesn't work

### ISSUE THREAD

**Issue by ilanbiala** [LearnBoost/mongoose#2574]
I've got a schema:
```
var UserSchema = new Schema({
  firstName: {
    type: String,
    trim: true,
    default: ''
  },
  lastName: {
    type: String,
    trim: true,
    default: ''
  },
  displayName: {
    type: String,
    trim: true
  },
  email: {
    type: String,
    trim: true,
    required: true,
    index: true,
    unqiue: true
  },
  isAdmin: {
    type: Boolean,
    default: false
  },
  provider: {
    type: String
  },
  providerData: {},
  updated: {
    type: Date
  },
  created: {
    type: Date,
    default: Date.now
  },
  status: {
    type: String,
    enum: [
      'Invited',
      'Created',
      'Pending invite'
    ],
    default: 'Invited'
  },
  orderHistory: [{
    type: Schema.Types.ObjectId,
    ref: 'Order',
    default: []
  }]
});
```
and when I save two documents with the same email, I don't get an error...why?

**Comment by vkarpov15** [comment]
You misspelled "unique" as "unqiue" - perhaps that could be the cause? Also, make sure that model's `index` event isn't returning any errors

**Comment by ilanbiala** [comment]
@vkarpov15 how do I check the index event? Is that something that will happen when I open a connection, or when I do something to the collection?

**Comment by vkarpov15** [comment]
Assuming that `User` is the model around `userSchema`

```
User.on('index', function(err) {
  // Log and throw
});
```

This event gets fired when mongoose is done creating any indexes on the server side - under the hood, `unique` creates a unique index on the mongodb server, so if index build fails this index might not actually have been created.
