### ISSUE TITLE
Setters don't get called when using document.set() with an object

### ISSUE THREAD

**Issue by juriejan** [LearnBoost/mongoose#2579]
Is it expected behaviour for the defined setters not to get called when providing an object to `document.set()`. They are called fine when using the field and value format of the function.

The following doesn't call the defined setters:

    doc.set({'field':'value'});

This, however, works as expected:

    doc.set('field', 'value');

**Comment by vkarpov15** [comment]
Nope, I think that's a bug. I'll investigate.

**Comment by vkarpov15** [comment]
Hmm you're going to have to provide me some more information. The following code works fine on 3.8.x and 4.0.0-rc2 for me, so I can't quite reproduce your issue:

```javascript
'use strict';

var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/myapp');

var x = function(v) {
  console.log(v);
  return 'name: ' + v;
};

var NameSchema = new mongoose.Schema({ name: { type: String, set: x } });

var Name = mongoose.model('Name', NameSchema, 'Name');

var n = new Name();
n.set('name', 'Val');
n.set({ name: 'Val2' });
console.log(JSON.stringify(n));
```

**Comment by juriejan** [comment]
I also can't seem to reproduce this error now. My apologies. I must have missed something when I reported this issue.

**Comment by vkarpov15** [comment]
Ok I'll close this issue. If it pops up again, feel free to reopen this one.
