### ISSUE TITLE
I cannot findOne query successfully

### ISSUE THREAD

**Issue by efkan** [LearnBoost/mongoose#2580]
I had written my routers using mongo-native-driver. Now, I've been trying to use Mongoose but I couldn't. With the below codes, I try to find a user from webUsers collection to authentication. 
If I try without model and mongoose and with native-driver I can get user as a console output.

What should I do?

My model  ../models/webUser.js ;
 
    var mongoose = require('mongoose'),
        ObjectId = mongoose.Schema.ObjectId;

    var webUserSchema = new mongoose.Schema({
        _id: ObjectId,
        username: String,
        password: String,
        name: String
    });

    module.exports = mongoose.model('webUsers', webUserSchema);

And my router    ../routes/session.js ;

    var express = require('express'),
        session = express.Router(),
        mongoose = require('mongoose'),
        webUser = require('../models/webUser');

    session.post('/login', function(req, res){
          webUser.findOne({username: req.body.username, password: req.body.password}, 
          function(err, user) { 
              console.log(err);    // NULL
              console.log(user);  // NULL
        })
     });

**Comment by Swissbite** [comment]
remove _id from schema and try again. This should work.

**Comment by efkan** [comment]
Hello @Swissbite,
Unfortunately it doesn't work. Also I've tried use `mongoose.connect(mongoDbURI);` in my model file. It should be easy :) I hope I learn how to use model today.

**Comment by efkan** [comment]
Thank you @Swissbite,

In the end I can find the solution!

I've replaced `module.exports = mongoose.model('webUsers', webUserSchema);` line with `module.exports = mongoose.model('webUser', webUserSchema, 'webUsers');`

It needs an implementation of (model_name, schema_name, collection_name).
Unfortunately I couldn't find anything regarding this issue on documentations for 2 days. 
If there are something like this trick please write :smiley:

**Comment by vkarpov15** [comment]
Yeah because if you don't specify a third parameter to mongoose.model, mongoose will attempt to infer the collection name from the model name.

**Comment by efkan** [comment]
So if my collection name is same as with model name I needn't use a third parameter.
Thank you..
