### ISSUE TITLE
Model.create(Array) promise is spreading arguments

### ISSUE THREAD

**Issue by jtmarmon** [LearnBoost/mongoose#2582]
@vkarpov15 mentions in #2478 that if you pass an array to `Model.create`, the promise is resolved with an array. However, [in the docs](http://mongoosejs.com/docs/api.html#model_Model.create it looks like the arguments are spread, and my code is showing the same. Would love some clarification here if possible

**Comment by vkarpov15** [comment]
3.8.x always returns them as a spread, 3.9.x (and 4.0) will return them as an array if you pass an array and spread if you pass in a spread. The reasoning for this is that it's a backwards breaking change, so needs to be in the unstable branch. 4.0 is currently waiting on MongoDB server 2.8 and MongoDB node driver 2.0 to stabilize before releasing.

**Comment by jtmarmon** [comment]
got it. thanks

**Comment by Soviut** [comment]
I created an issue about this regarding the callback as well https://github.com/LearnBoost/mongoose/issues/2602

**Comment by jtmarmon** [comment]
oy this came back and bit me again. For anyone who stumbles upon this, Q and Mongoose basically have opposing philosophies (until 3.9/4.0).  see https://github.com/kriskowal/q/issues/357

**Comment by vkarpov15** [comment]
Yeah Q doesn't support resolving with a spread, but mongoose's underlying library `mpromise` does. Technically, neither promises/A+ spec nor ES6 spec explicitly prohibits resolving with a spread, although ES6 implies only a single value. To work around this, in 3.9.x and upcoming 4.x, `Model.create()` will return a spread if you passed it a spread and an array if you passed it an array.

**Comment by jtmarmon** [comment]
Actually what just occurred to me is that I could use `Q.spread`. Still confusing though. Gonna be excited to get arrays back in 4.0
