### ISSUE TITLE
findOneAndRemove deletes wrong user

### ISSUE THREAD

**Issue by ilanbiala** [LearnBoost/mongoose#2583]
I have confirmed that the id I am passing in is correct by logging, and doing a `findOne` produces the right document. Any ideas on what isn't working?

```
User
    .findOneAndRemove(req.profile._id)
    .exec(function(err, user) {
      if (err) {
        return res.status(500).json({
          message: errorHandler.getErrorMessage(err)
        });
      } else {
        return res.json(user);
      }
    });
```

**Comment by vkarpov15** [comment]
Perhaps because you have a malformed query? I think it should be `.findOneAndRemove({ _id: req.profile._id })`

**Comment by ilanbiala** [comment]
@vkarpov15 I'll try that, at one point I did see it accepts id directly, but the big issue I think with the docs is that there aren't enough examples that show basic and advanced usage. Any plans on expanding docs for 4.0.0?

**Comment by Swissbite** [comment]
@ilanbiala I think you have seen the function [findByIdAndRemove](http://mongoosejs.com/docs/api.html#model_Model.findByIdAndRemove). The differerence is that findOne uses objects for finding (like mongo does) and findById is syntatic help.

findByIdAndRemove does an internal call to:
```javascript
return this.findOneAndRemove({ _id: id }, options, callback);
```

**Comment by vkarpov15** [comment]
@Swissbite is right, there's a separate `findByIdAndRemove()` function for that use case. Improving and rethinking the docs is a priority but that will be after 4.0 is released.

**Comment by ilanbiala** [comment]
@Swissbite thanks for the help!

**Comment by Aymenob** [comment]
i know this is an old post but i m getting the same issue on i used console log in front end to check if m sending the right id on req.params.id and i used all different methodes like .findByIdAndDelete() but it still deletes the wrong user . any updates on this ?

**Comment by Uzlopak** [comment]
Thats not very specific. Maybe you should set strictQuery to false.

**Comment by Aymenob** [comment]
okay so now i know that the payload of my request contain the right Id (checked it with redux Dev tools), but the id that is recivied in the back end is  the previous one , i m using mongoose so i will try to find out why that is happening

**Comment by Aymenob** [comment]
update: the id recived on the back end is the right one, but its 
    
   let user=await Users.findOne({userId}) that is giving me the wrong user

**Comment by Aymenob** [comment]
okay so i solved it : it seems weird but since my route on express is :"router.delete("/deleteUser:id",deleteUser)"
and i 'm using axios request like this : axios.delete("http://localhost:8081/deleteUser":+userID)
i used to get the previous used with model.findOne() on mongoose and all i had to do is removing the ":"
and now its working fine .
