### ISSUE TITLE
Reverse populating with 'ref' keywords

### ISSUE THREAD

**Issue by efkan** [LearnBoost/mongoose#2585]
Hello,
Sometimes I remember that question for years; "why we cannot populate reverse two table(in this case collection)". Assuming one way. In any case we control a child record from parent record. Why we need child_id in a parent collection?

I want to store parent_id in my children collection and I don't want to store child_id in my parents collection.
I couldn't find anything regarding this issue. Is it possible?
If it's not possible then it should have a reason.

For Example **parents collection**;

    {
        _id: ObjectId("123456abcde"),
        name: "Michael"
    }

**a parent model**; I should write a reference like this `children: [ { type: ObjectId, ref: 'child.parent_id' } ]`
  
    {
        _id: ObjectId,
        name: String,
        children: [ { type: ObjectId, ref: 'child' } ]
    }

**children collection**
  
    {
        _id: ObjectId("654321edcba"),
        parent_id: Object("123456abcde"),
        name: "Jason",
     },
     {
        _id: ObjectId("70000edcba"),
        parent_id: Object("123456abcde"),
        name: "Alice",
     }  

**a child model**

    { 
        _id: ObjectId,
        parent_id: ObjectId,
        name: String
     }

with this method I can remove a child.

**Comment by Swissbite** [comment]
Why should you not be able to store parant_id as a references? This is working very well. 
```javascript
{ 
    parent_id: {type: ObjectId, ref: 'parent'} ,
    name: String
 }
```
Even populate will work in this case.
But if you have a parent and you would like to search all children, you will have to search over the child collection:

```javascript
Child.find({parent_id: YOUR_PARENT_ID}, callback)
```
But if you want to be able to populate all children from a parent directly, you may have to make references on both schema and work with hooks for creating and deleting children

PS: This model defines that a child has only one parent. You may either define mum and dad or parent_1 and parent_2 or use an array for parent_ids

**Comment by efkan** [comment]
Hello,

Yes, assume I have a parent and you would like to search all children. I want :) to add a new child or delete an existing child using a Mongoose Model.

I understand. Mongoose has not an option like this. 
Thank you.
