### ISSUE TITLE
Field that is an object and validators (on 3.9.x)

### ISSUE THREAD

**Issue by julien-maurel** [LearnBoost/mongoose#2590]
Hi,
If have an issue with schema that have a field that contains an object.
I can write it at different formats : 

```
// like this, o.a is mandatory (=>ok) but o too, I can't add a document without o specified
var s = new schema({
    title:String,
    o:{
        a:{
   	    type:String,
	    required:true
	},
	b:String
    }
});
```
```
// like this, o is not mandatory but o.a is not too (=>not good)
var s = new schema({
    title:String,
    o:{
	type:{
	    a:{
		type:String,
		required:true
	    },
	    b:String
	}
    }
});
```
```
// like this, crash because field can't content an sub doc if it's not an array of sub docs
var s1 = new schema({
    a:{
	type:String,
	required:true
    },
    b:String
});
var s2 = new schema({
    title:String,
    o: s1
});
```

I don't know if each syntax work well or if there an issue.

**Comment by vkarpov15** [comment]
Hi,

I'm not sure I understand, can you please clarify what the issue is?

**Comment by julien-maurel** [comment]
In fact, I try to have a model that have a field "o" that is an object that contains "a" and "b".
I would like "a" and "b" properties of "o" are mandatory only if field is give.
e.g : 
{title:"rr"} => ok because "o" is not given
{o:{}} => ko because "o" is given but not "o.a"
{o:{a:"r"}} => ok because "o" is given and "o.a" too

So I tried these syntax : 
```
var s = new schema({
    title: String,
    o:{
        a:{
            type:String,
            required:true
        },
        b:String
    }
});
=> with that I can't insert a doc without o and o.a (o became mandatory)
```
```
var s = new schema({
    title: String,
    o:{
        type:{
            a:{
                type:String,
                required:true
            },
            b:String
        },
        required: false
    }
});
=> with that I can insert a doc without o but I can insert a doc with o, o.b but not o.a because validators are not run
```
```
var o = new schema({
    a:{
        type:String,
        required:true
    },
    b:String
});
var s = new schema({
    title: String,
    o:{
        type:o,
        required:false
    }
});
=> with that I have error that say Nested schema are only on array
```

I think first syntax is a correct syntax but that not respond to my need
After some tests, I think second syntax is completely wrong :)
And about third, doc say we can use nested doc only on array, so it's normal.
So finaly, perhaps my issue is just that there is no way to do what I need easily. Right?

**Comment by Swissbite** [comment]
That is true. Currently, if there is any required, then the value/field has always to be set.

What you could do is using a custom validator.

That may be a way. This validator is not testet, it's writen just here. So be careful with copy/paste

```javascript
function validate(o) {
   if(!o || o.a) {
    return true;
  }
  return false;
}

var s = new Schema({
  title: String,
  o:{ 
    type: {
        a: String,
        b: String
    },
    validator: validate
  }
});
```

**Comment by julien-maurel** [comment]
I thought to that and I'll try to do it tomorrow to solve my problem.
It's easy to do to solve required validator, but I have similar issue with match or any other validators.
But in any case, with custom validate, I can do what I want so I would always this solution ;)
Thanks.

**Comment by vkarpov15** [comment]
Yeah a custom validator is the right way to do it. The second syntax you provided is not right - type shouldn't be an object like that. Thanks @Swissbite 

And as for `match`, the `match` validator will only run if `o.a` is defined, so that shouldn't be a problem with your use case. But if it isn't, custom validator works

**Comment by joetconcur** [comment]
@vkarpov15, you said the second syntax in @Swissbite's example was not right - type shouldn't be an object. So the type should be Schema.ObjectId? Can you provide the correct example? Thanks.

**Comment by vkarpov15** [comment]
I was incorrect - I thought you were trying to create a dynamic type. Mongoose does support fields named `type`, so that example is correct.

**Comment by joetconcur** [comment]
I see. Thanks.
