### ISSUE TITLE
Saving string when field is nested object

### ISSUE THREAD

**Issue by karaxuna** [LearnBoost/mongoose#2592]
My Item Schema:

    new Schema({
        name: {
		    ka: String,
		    en: String
	    }
    });

When doing like this:

    Item.findOne({}, function(err, item){
        item.name = 'wrongtype';
        item.save();
    });

item's name property is saved to database, despite of fact that name is described as object in schema. [SO reference][1]. Version 3.8.21

  [1]: http://stackoverflow.com/questions/27925821/saving-string-when-field-is-nested-object

**Comment by vkarpov15** [comment]
Not sure, I'll investigate this. Thanks for opening up an issue.

**Comment by vkarpov15** [comment]
This may be backwards breaking, so I'm putting it in 4.0. Thanks for catching this bug though, its a pretty odd quirk that's been in mongoose for a long time. Looking forward to seeing it fixed and stable :)
