### ISSUE TITLE
On "auth failed" Mongoose prevents exit of the process

### ISSUE THREAD

**Issue by Koblaid** [LearnBoost/mongoose#2599]
The following script won't exit. It prints 
```{ [MongoError: auth failed] name: 'MongoError', ok: 0, errmsg: 'auth failed', code: 18 }```
and hangs forever.

```javascript
var mongoose = require('mongoose');
mongoose.connect('mongodb://x:y@localhost', function(err){
  console.log(err);
  mongoose.connection.close();
});
```

Tested with mongoose@3.8.21 on Linux.

**Comment by vkarpov15** [comment]
Thanks, I'll investigate.

**Comment by Koblaid** [comment]
Thanks :-)
