### ISSUE TITLE
Populated Objects and Form Posts

### ISSUE THREAD

**Issue by timothysoehnlin** [LearnBoost/mongoose#2601]
I'm attempting to form post an object (that had references populated) back to Node.js and ultimately through Mongoose to be saved to the database.  The issue I am currently running into, is that the populated objects, upon passing to the model constructor, are being removed.  I'm assuming this is due to validation as the types to do not match: the field is expecting ObjectId, but getting an JS Object, with an _id field.  

Is there anyway to force mongoose to accept these, or to coerce the populated object back into an ObjectId? 

My current solution is to flatten all populated objects of the posted object into the scalar value of the _id field.  

Thanks!

**Comment by vkarpov15** [comment]
Flattening is the only way currently
