### ISSUE TITLE
Model.create() should return an array when creating multiple documents at once

### ISSUE THREAD

**Issue by Soviut** [LearnBoost/mongoose#2602]
Currently, `Model.create()` accepts single objects or an array of objects to create documents. The callback then receives the created documents as individual arguments, one for each document.

```javascript
var users = [
    {username: 'first'},
    {username: 'second'}
];
User.create(users, function(err, first, second) {
    // notice first and second are individual arguments
});
```
This feels very unintuitive as I would expect that if I'm supplying an array, I'd receive an array in the callback. It also makes dealing with the results very difficult when there are variable numbers of objects being created. I've had to use the `arguments` keyword in combination with a helper function just to get it into an array.

I propose the callback should receive an array of documents that corresponds to the supplied array of objects. Like so:
```javascript
User.create(users, function(err, users) {
    users.forEach ...
});
```

**This would also mean a breaking change so a bump to 4.0 would be in order.**

**Comment by vkarpov15** [comment]
Already in 3.9.x, will be in v4, which is currently waiting on the next version of the MongoDB core server to be released (current ETA early Feb)
