### ISSUE TITLE
using post hook dramatically increases cpu & RAM usage & hangs server

### ISSUE THREAD

**Issue by programming-kid** [LearnBoost/mongoose#2614]
i don't understand this problem using a simple post save hook dramatically increase cpu usage and cpu temp and hangs server indefinitely 

```javascript
MessageSchema.post('save', function (doc) {
    var id = hashids.encode(doc.message_num);
    doc.shortUrl = id;
    doc.save();
});
```
node : 0.10.26
mongoose : 3.8.18 & also 3.8.22

pls help 

thanks

**Comment by Swissbite** [comment]
Because you made an infinite loop.

Every time you save the doc, the hook will be called.
And because you call it within a post hook....

Why do you not use the previous hook and just add the short url to the doc?

**Comment by Swissbite** [comment]
Sorry, auto correction. I ment pre hook

**Comment by vkarpov15** [comment]
Yeah @Swissbite is right - you have an infinite loop. You're going to keep calling save indefinitely. `pre('save')` is the right place for this task.

**Comment by namnguyen2091** [comment]
> Yeah @Swissbite is right - you have an infinite loop. You're going to keep calling save indefinitely. `pre('save')` is the right place for this task.

But pre hook, I can only get doc from request not full doc from database. Assum I have a field A only update when its not exists, if i dont use post hook i cant get A field existing in doc. How should I do?

**Comment by vkarpov15** [comment]
@namnguyen2091 check before saving. There's nothing especially wrong with calling `save()` in a `post('save')` hook as long as you avoid infinite recursion. Borrowing OPs example:

```
MessageSchema.post('save', function (doc) {
    if (doc.shortUrl) {
      return;
    }
    // Set `shortUrl` if it isn't already set
    var id = hashids.encode(doc.message_num);
    doc.shortUrl = id;
    return doc.save();
});
```
