### ISSUE TITLE
required validator always run on fields inside optional object field?

### ISSUE THREAD

**Issue by joetconcur** [LearnBoost/mongoose#2622]
var mongoose = require('mongoose'),
          Schema = mongoose.Schema;

    var ASchema = new Schema({
        detail: {
            name: {type: String, required: 'Required field "{PATH}" is missing'},
            optionalChild: {
                requiredField: {type: String, required: 'Required field "{PATH}" is missing'}
            }
        }
    });
    
    var AModel = mongoose.model('A', ASchema);
    var a = new AModel();
   
    // this is a valid object 
    var sampleDetail = {
        name: 'sample 1'
    };

    a.detail = sampleDetail;
    a.save(function(err, obj) {
        if (err) {
            // error 'Required field "detail.optionalChild.requiredField" is missing'
        }
    });

What I wanted to have is that when the optionalChild is not specified, just skip the required validation on requiredField. And when the optionalChild is there, ensure that the requiredField is present.

Is there a way to do this properly?

Thanks!

**Comment by Swissbite** [comment]
You could use a custom validator.

See https://github.com/LearnBoost/mongoose/issues/2590#issuecomment-69620720 as an example.

**Comment by vkarpov15** [comment]
Yeah @Swissbite is right, this is a job for a custom validator. `required` won't support that anytime in the near future.

**Comment by joetconcur** [comment]
Thanks for the answer, Swissbite, vkarpov15.
