### ISSUE TITLE
After getting a mongoose model by name, mongo's collection.remove() will never callback.  (version 3.9.8-pre)

### ISSUE THREAD

**Issue by rolandnsharp** [LearnBoost/mongoose#2627]
This works fine in 3.8.x as far as I can tell and I can't find any reference as to why it would be made redundant. 
```
Model = mongoose.model('modelName');
Model.collection.remove(function(err){
    console.log("I'm never called.");
});
```

Model.collection seems to be a mongo object and collection.find() works, but something is wrong with remove().

**Comment by vkarpov15** [comment]
Which 3.9.x? 3.9.7, HEAD?

**Comment by rolandnsharp** [comment]
I'm experianceing this on the current master branch.
So as of right now: 3.9.8-pre and SHA: d2ccf20ae88962548437de3d54a7949c2da0f93b

**Comment by rolandnsharp** [comment]
```
Model.collection.remove({}, function(err) {
    console.log('Using an empty object at the first argument fixes the bug.');
});
```

**Comment by vkarpov15** [comment]
So passing an empty object to `remove()` is [the correct way of doing it](http://docs.mongodb.org/manual/tutorial/remove-documents/). I seem to remember support for remove without specifying a query being deprecated at some point. But the fact that there's no callback seems like a bug. I'll look into this.

**Comment by vkarpov15** [comment]
Issue with the new node driver, see mongodb/node-mongodb-native#1247

**Comment by AhmetEmsal** [comment]
Is something like this correct to get the model by collection name ?
```js
let collectionName = 'clubs';
let modelOfCollection = mongoose.connection.models[mongoose.connection.collections[collectionName].modelName];
```

**Comment by vkarpov15** [comment]
@AhmetEmsal that should work
