### ISSUE TITLE
Docs error: wrong parameter order for distinct()

### ISSUE THREAD

**Issue by EgoAleSum** [LearnBoost/mongoose#2628]
The docs ( http://mongoosejs.com/docs/api.html#query_Query-distinct ) say that the parameter order is: `Query#distinct([criteria], [field], [callback])`.

After wasting 30 minutes with a very obscure error when using all 3 arguments, I found out that the parameter are actually reversed: `Query#distinct([field], [criteria], [callback])`. This works.

**Comment by vkarpov15** [comment]
Well that's embarrassing. Fixed. Thanks for pointing that out.

**Comment by vkarpov15** [comment]
Actually, the docs are correct: `distinct()` queries take field and criteria in reverse order. So:

```
Model.distinct(field, criteria, callback)
```

But

```
Model.find().distinct(criteria, field, callback);
```

I never noticed this, its a really bad design decision that predates my involvement in mongoose. Going to fix this now. Unfortunately, its backwards breaking, so it won't go in to 3.8.x.

**Comment by EgoAleSum** [comment]
MongoDB's APIs use (field, criteria) ( http://docs.mongodb.org/manual/reference/method/db.collection.distinct/ ). I think this order would be the most consistant?

Anyways, I'm not sure I understood exactly: what's the final call? What changes now and what will change on 3.0?

Thanks for taking care of this

**Comment by vkarpov15** [comment]
Mongoose will be consistent with the MongoDB API in 4.0: it will be `distinct(field, criteria, callback)`

**Comment by EgoAleSum** [comment]
And for now it will be like this?

    Model.distinct(field, criteria, callback)
    Model.find().distinct(criteria, field, callback)

So the only change in 4.0 is with the `Model.find().distinct()`? That works for me. Thanks!

**Comment by vkarpov15** [comment]
Yeah exactly. Both cases will be `field, criteria`
