### ISSUE TITLE
Defaults do not apply when you select an object node

### ISSUE THREAD

**Issue by dpatti** [LearnBoost/mongoose#2629]
What I'm trying to do is select an entire object using just its root. Like so:

```javascript
model.find(query).select({ obj: 1 })
```

And it does indeed return the document with this initialized. However, if you have keys on that `obj` above with defaults, the paths are not initialized unless you specifically include those or they are present in the raw document. If a new default was added to the old schema, it would not be filled in on old documents that are fetched using this selector. If *no* selector is used, the defaults are present. The only other option is to use dotted notation for each key:

```javascript
model.find(query).select({ 'obj.inner': 1 })
```

It looks like the problem is simply because [it only checks if the full path is in the selected fields](https://github.com/LearnBoost/mongoose/blob/master/lib/document.js#L214-L221).

This is a failing test that I believe describes the problem:

```javascript
  it('initializes nested defaults with selected objects', function(done){
    var NestedSchema = new mongoose.Schema({
      nested: {
        array: [String],
      }
    });

    var db = start();
    var Model = db.model('nested', NestedSchema);

    var doc = new Model();
    // We have to emulate saving this document before we added 'nested.array' to our schema.
    doc.nested.array = undefined;
    doc.save(function(error){
      assert.ifError(error);
      Model.findOne({}, { nested: 1 }, function(error, doc){
        assert.ifError(error);
        assert(doc.nested.array instanceof Array);
        done();
      });
    });
  });
```

**Comment by vkarpov15** [comment]
Thanks for the detailed report. I'll look into this next week.

**Comment by dpatti** [comment]
Thanks for the fix!
