### ISSUE TITLE
Pre-save hooks on nested subdocs are broken

### ISSUE THREAD

**Issue by ashaffer** [LearnBoost/mongoose#2634]
But it is being masked by asynchronous validation running extra times.

In using my pull #2625 in our internal project, I noticed that pre-save hooks stopped blocking saves in all cases.  This is because the logic around .save()'ing nested subdocs is incorrect when the hooks are synchronous.  It isn't an issue in mongoose right now, but only because the way validation is running forces them to be asynchronous.

My most recent commit on that branch has a fix and test for it:

https://github.com/ashaffer/mongoose/commit/723fe0f8080c268b361a86652251b27d0c34c660

Though the test will obviously not fail in the main 3.8.x branch, and it isn't an issue per se, it seems like something that should be fixed because the implementation is highly misleading.

**Comment by vkarpov15** [comment]
Hmm you're going to have to clarify this. If the test doesn't fail, what's the issue?

**Comment by ashaffer** [comment]
Mongoose is computing the `subdocs` length incrementally, while simultaneously decrementing it when hooks complete.  If, however, all of the hooks are synchronous, subdocs can reach zero before processing all of the documents.

**Comment by vkarpov15** [comment]
The way pre hooks are implemented, they are necessarily async, no other way to do it. Why should subdocs length calculation be changed to fit a false assumption?

**Comment by vkarpov15** [comment]
Gonna close - reopen if there's a reproduceable issue :)
