### ISSUE TITLE
Creating custom SchemaTypes (mongoose 3.8.12)

### ISSUE THREAD

**Issue by kallisti-dev** [LearnBoost/mongoose#2638]
Hello! So I'm creating a custom SchemaType, following mongoose-long as a reference. However, I  encountered a problem when using my SchemaType within a SchemaArray.

Here's a summary of my environment for reference
* Node: 0.10.33
* MongoDB: 2.4.12
* mongoose: 3.8.12

The issue should be reproducible using the following code
```javascript
'use strict';
var mongoose = require("mongoose");
var util = require("util");

function MySchemaType(path, options) {
    mongoose.SchemaType.call(this, path, options, 'MySchemaType');
};

MySchemaType.prototype.cast = function(val, doc, init) {
    console.log("casted");
    return val;       
};

util.inherits(MySchemaType, mongoose.SchemaType);

var mySchema = new mongoose.Schema({
    path: [MySchemaType]
});


mongoose.connect("mongodb://localhost:27017/mydatabase", {
    user: "myuser",
    pass: "1234"
});

var db = mongoose.connection;

db.once("open", function() {
    var MyModel = mongoose.model("MyModel", mySchema);
    MyModel.create( {path: 0}, function(err, obj) {
        if(err) throw err;
        console.log("object created");
        obj.path = 1;
        obj.save(function(err) {
            if(err) throw err;
            console.log("saved");
        });
    });
});
```

I get the following exception when executing this code

```
.../node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:245
        throw message;
              ^
CastError: Cast to undefined_method failed for value "0" at path "path"
    at SchemaArray.cast (.../node_modules/mongoose/lib/schema/array.js:149:15)
    at SchemaArray.cast (.../node_modules/mongoose/lib/schema/array.js:155:17)
    at SchemaArray.SchemaType.applySetters (...node_modules/mongoose/lib/schematype.js:526:17)
    at ...node_modules/mongoose/lib/document.js:544:18
    at model.Document.$__try (.../node_modules/mongoose/lib/document.js:757:8)
    at model.Document.set (.../node_modules/mongoose/lib/document.js:543:24)
    at model.Document.set (.../node_modules/mongoose/lib/document.js:454:18)
    at model.Document (.../node_modules/mongoose/lib/document.js:60:10)
    at model.Model (.../node_modules/mongoose/lib/model.js:43:12)
    at new model (.../node_modules/mongoose/lib/model.js:2502:11)
```

I saw that the "real" exception was being caught and then rethrown as a CastError. Changing line 149 of schema/array.js to be ``throw e`` to reveal the original exception, I get the following stacktrace:

```
...node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:245
        throw message;
              ^
TypeError: Object #<MySchemaType> has no method 'cast'
    at SchemaArray.cast (...node_modules/mongoose/lib/schema/array.js:145:34)
    at SchemaArray.cast (...node_modules/mongoose/lib/schema/array.js:156:17)
    at SchemaArray.SchemaType.applySetters (...node_modules/mongoose/lib/schematype.js:526:17)
    at ...node_modules/mongoose/lib/document.js:544:18
    at model.Document.$__try (...node_modules/mongoose/lib/document.js:757:8)
    at model.Document.set (...node_modules/mongoose/lib/document.js:543:24)
    at model.Document.set (...node_modules/mongoose/lib/document.js:454:18)
    at model.Document (...node_modules/mongoose/lib/document.js:60:10)
    at model.Model (...node_modules/mongoose/lib/model.js:43:12)
    at new model (...node_modules/mongoose/lib/model.js:2502:11)
```

So it would appear that MySchemaType is not being instantiated before use as a caster, but I can't pinpoint exactly where this occurs. Additionally, if I remove the following line from my original example:

```javascript
util.inherits(MySchemaType, mongoose.SchemaType);
```

Everything works as expected:

```
$ node issue.js
casted
object created
casted
saved
```

I'm not sure if this is a bug necessarily, but it's definitely confusing for someone attempting to write their own schema types. Any clarification on why inheriting from SchemaType is causing the above error would be appreciated.

**Comment by kallisti-dev** [comment]
Just to make sure the problem hasn't already been fixed, I ran the above code against mongoose 4.0.0-rc1 (current latest version) and got identical errors (the source line changed, but the error message was the same).

**Comment by vkarpov15** [comment]
Thanks for the detailed report, on it.

**Comment by vkarpov15** [comment]
So this is actually an issue with how you're using `util.inherits()`. Here's the implementation of `util.inherits()` in NodeJS 0.10.30:

```javascript
function (ctor, superCtor) {
  ctor.super_ = superCtor;
  ctor.prototype = Object.create(superCtor.prototype, {
    constructor: {
      value: ctor,
      enumerable: false,
      writable: true,
      configurable: true
    }
  });
}
```

You'll notice that it overwrites the prototype, rather than just copying over properties like you might expect. This means that `util.inherits()` is wiping out the object you attached the `MySchemaType.prototype.cast()` function to. The below code works:

```javascript
'use strict';
var mongoose = require("mongoose");
var util = require("util");

function MySchemaType(path, options) {
    mongoose.SchemaType.call(this, path, options, 'MySchemaType');
};

// Note that the inherits() call is **before** the declaration of cast
util.inherits(MySchemaType, mongoose.SchemaType);

MySchemaType.prototype.cast = function(val, doc, init) {
    console.log("casted");
    return val;       
};

var mySchema = new mongoose.Schema({
    path: [MySchemaType]
});


mongoose.connect("mongodb://localhost:27017/mydatabase");

var db = mongoose.connection;

db.once("open", function() {
    var MyModel = mongoose.model("MyModel", mySchema);
    MyModel.create( {path: 0}, function(err, obj) {
        if(err) throw err;
        console.log("object created");
        obj.path = 1;
        obj.save(function(err) {
            if(err) throw err;
            console.log("saved");
        });
    });
});
```

**Comment by kallisti-dev** [comment]
Ah I see. Thanks for the help. Just a quick additional question: aside from castForQuery (which I've already implemented, but omitted from this issue due to irrelevance), are there any other methods I should be looking to define for custom schema types?

**Comment by kallisti-dev** [comment]
I'll likely update the documentation with a guide on creating SchemaTypes. Correct me if I'm wrong, but I don't think there's a detailed guide on it beyond a recommendation to look at the source of existing mongoose plugins.

**Comment by vkarpov15** [comment]
Nope there's definitely a lack of documentation on that front. Any help would be most appreciated :) As a matter of fact, I don't really know the answer right now. `cast()` and `castForQuery()` are the only ones I can think of off the top of my head, but I'm not 100% sure those are the only ones. Documentation would help me too :)
