### ISSUE TITLE
SchemaType casting error

### ISSUE THREAD

**Issue by jeffdupont** [LearnBoost/mongoose#2641]
Is there a way to bypass the SchemaType to update a value to the correct SchemaType??
I have a document that has an updated_at value in Mongo that is an ISODate() and we're trying to update all documents to use a Number for a timestamp instead. But I'm getting a CastError "Cast to number failed for value \"Mon Feb 02 2015 13:33:02 GMT-0700 (MST)\" at path \"updated_at\"" even though I have manually changed the updated_at value to a timestamp before .save()

**Comment by vkarpov15** [comment]
I wouldn't recommend doing this in general, but you can work around this by calling `doc.$__reset()` after  loading the doc to clear the error state.

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost:27017/gh-2641');

var s = new Schema({ t: Date });
var s2 = new Schema({ t: Number });

var M = mongoose.model('m', s, 'gh-2641');
var M2 = mongoose.model('m2', s2, 'gh-2641');

var x = new M({ t: new Date() });
x.save(function(err, doc) {
  console.log('err1: ' + err);
  console.log('Doc saved: ' + JSON.stringify(doc));
  M2.findOne({ _id: x._id }, function(err, doc) {
    console.log('err2: ' + err);
    console.log('Doc: ' + JSON.stringify(doc));
    // This clears the doc's error state
    doc.$__reset(); // <----------

    doc.t = 0;
    doc.save(function(err) {
      console.log('err3: ' + err);
      M2.findOne({ _id: x._id }, function(err, doc) {
        console.log('Result: ' + JSON.stringify(doc));
      });
    });
  });
});
```

**Comment by jeffdupont** [comment]
Because of the way my code structure is setup, introducing a second Schema was extremely difficult. So, instead I ran a raw mongo update against the model "Model.update()" and passed in the timestamp integer to be saved. This seemed to work and allows the application to correctly update the values later on within the code.

Thanks for the assistance!

**Comment by vkarpov15** [comment]
@jeffdupont that works too, and is actually probably the better solution. In general, mongoose isn't a very good tool for handling schema migrations - I generally just write a mongodb shell script to make these kinds of changes to my data. Going forward I've been looking to try playing with [migroose](https://github.com/derickbailey/migroose-cli), and I also envision this as a core use case for tools like [nimrod](https://github.com/vkarpov15/nimrod), but for now shell is probably best :)
