### ISSUE TITLE
Random and unpredictable Maximum call stack size exceeded during heavy load

### ISSUE THREAD

**Issue by poupougnac** [LearnBoost/mongoose#2643]
Hi,

I'm using 3.18.22. For 3 months now, I have some random crash on my Heroku app.

Error messages are related to mongoose but are always different except that part : 

```
/node_modules/mongoose/node_modules/mpath/lib/index.js:39
    ? path.split('.')
           ^

RangeError: Maximum call stack size exceeded
```
I always have the stack size problem, it appears randomly but always somewhere inside the mongoose module. (many time in util.js). I can reproduce it with a simple REST benchmarking tool.

## What I'm doing : 

I have a function that update a count value field in my collection "Products"
I have another function which is doing an expensive aggregate() call to count the sum of all product in my Products collection. 

I execute one update, then one aggregate through REST calls (one call = one function executed). And I start over. 

It works until ~500 products then the aggregate function tends to slow down then this error occurs. 

I would like to know what would be my best approach for this issue ? I can scale but it seems for me not normal that even under heavy load, this error appears (something related to memory issue or  would have been clever for me)

Can it be a mistake in my code even if the crash occurs anytime and anywhere when the system has to handle many simultaneous calls (1000 calls with 10 simultaneous connections). ? At a normal pace, the application don't cause any crash. 

Thank you
(sorry for my approximate english)

**Comment by vkarpov15** [comment]
Hmm I don't see anything obvious. What does your aggregation pipeline look like? Is the output just a single number or something with much more data?

**Comment by poupougnac** [comment]
My aggregate function is (translated from coffeescript) :
``` javascript
products.count({}, function(err, nbProducts)->
      match = { $match : category:"mycat" }
      group = {
        $group:
          _id : "$category",
          totalnbProducts : $sum:"$quantity"
        }
      products.aggregate match, group, function(err,result) {
          result.nbProducts = nbProducts;
          res.send(result);
      });
  });
```

I'm just doing a count before the aggregation. If this is still not obvious, I will create a dedicated code to reproduce more easily the crash.

**Comment by vkarpov15** [comment]
Dedicated code would be helpful. My guess is that somewhere something is calling `.apply()` with a very big array, sorta like #2423, but I don't see anywhere this would be happening.

Also, just to help bisect this issue between mongoose or the node driver, can you try using `products.collection.aggregate([match, group], function(err, result) {})` and see if that also gets this error?

**Comment by poupougnac** [comment]
Actually when trying to replicate the issue somewhere else, I have found what caused the crash.
It was related to mongoose-auto-increment. I needed a flexible schema in my app and calling several time  `....plugin(autoIncrement.plugin, '...');`on the same schema cause a crash until a certain amount of calls. But it was my mistake to call that plugin several time, I sat a flag and now I'm clear. Thank you for your help.
