### ISSUE TITLE
Nested: question

### ISSUE THREAD

**Issue by Trevogre** [LearnBoost/mongoose#2644]
The documentation says I can do this.

```
nested: {
    stuff: { type: String, lowercase: true, trim: true }
  }
})

m.nested.stuff = 'good';
```

But can I do this?

```
nested: {
    type: String, 
    lowercase: true, 
    trim: true
    stuff: { type: String, lowercase: true, trim: true }
  }
})

m.nested = 'thats';
m.nested.stuff = 'good';
```

The purpose would be so that I could do.

```
myvalue: {
     type: String,
     trim: true,
     mycustomvalidationrequirements: {
            shouldshowonlyifsomecondition: { type: Boolean, default: false }
     }
```

I would rather do that that have to have a separate field value to store dependencies. 
Maybe that works already and I just haven't tested it. Maybe you can do this and mongoose only parses out the reserved words? 

Any thoughts? Maybe there is already an child object where you can pass arbitrary settings to the client. 

I know that I could do 

```
myvalue: {}
myvaluesettings: { required {}, color {} }
```

It just seems like it would be much nicer to just have those things under the field but still have the field have a value.

**Comment by vkarpov15** [comment]
I have used this before to a limited extent by associating functions with paths, sorta like:

```javascript
{ name: { type: String, shouldHide: function() {} } }
```

In other words, you won't be able to write to `m.nested.stuff` on a document (if you want to do that, you should use a virtual), but you can read/write to `stuff` in the schema itself. For instance,

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost:27017/gh-1548');

var s = new Schema({
  nested: {
    type: String, 
    lowercase: true, 
    trim: true,
    stuff: { type: String, lowercase: true, trim: true }
  }
});

var M = mongoose.model('gh-2644', s);

var m = new M();
m.nested = 'str';
m.nested.stuff = 'bacon';

console.log(m.nested);
console.log(m.nested.stuff);

console.log('\n-------\n');
s.eachPath(function(path, properties) {
  console.log(path + ' ' + require('util').inspect(properties.options.stuff));
});
```

The above code outputs

```
str
undefined

-------

nested { type: [Function: String], lowercase: true, trim: true }
_id undefined
__v undefined
```
