### ISSUE TITLE
Is mongoose support shard mongodb?

### ISSUE THREAD

**Issue by wanzhou** [LearnBoost/mongoose#2651]
Why I can't insert data by storage process in nodejs with mongoose after deploy the mongodb as a distribution. But it can work very well when I don't shard the collections.

**Comment by vkarpov15** [comment]
I'm afraid I don't quite understand the question. Can you elaborate?

**Comment by wanzhou** [comment]
@vkarpov15 
I wanna insert data into shard collections by calling mongodb storage function ( `db.eval()` ), but it's error ( can't call `db.evla()` with shard collections ). How can I achieve it. Sorry for my bad english!

**Comment by vkarpov15** [comment]
Unfortunately the mongodb server itself [doesn't allow `eval()` on sharded collections](http://docs.mongodb.org/manual/reference/method/db.eval/#sharded-data). Since the server prevents you from doing this, there isn't much that mongoose can do about it.

**Comment by wanzhou** [comment]
@vkarpov15 
I know, Thanks very much!
