### ISSUE TITLE
Updating document does not save embedded array

### ISSUE THREAD

**Issue by Persader** [LearnBoost/mongoose#2654]
```javascript
var CraData = new mongoose.Schema({
    task: String,
    time: Number,
    day: Number

});

var Cra = new mongoose.Schema({
    month: Number,
    year: Number,
    userId: Number,
    validationDate: Date,
    data: [CraData]
});

var CraModel = mongoose.model('Cra', Cra);

var cra = {// From json request parameters};
```

```javascript
    CraModel.findOne()
        .where('userId').equals(req.user.id)
        .where('month').equals(cra.month)
        .where('year').equals(cra.year)
        .exec(function(err, doc) {
            if (doc) {
                new CraModel(cra).update(identifier(cra) ,function (err) {
                    if (err) {
                        console.log(err);
                        res.json({error: true, msg: JSON.stringify(err)});
                    }
                    else {
                        console.log(JSON.stringify(cra));
                        res.json({success: true, cra: cra})
                    }
                })
            } else {
                new CraModel(cra).save(function (err) {
                    if (err) {
                        res.json({error: true, msg: JSON.stringify(err)});
                    }
                    else {
                        res.json({success: true, cra: cra})
                    }
                })
            }
        });
```

When saving cra for the first time, array of CraData is saved in database with success. When updating existing document, data are not updated.

If I use update method with options {upsert: true} at the first time (empty collection), data are not saved.

I tried to mark data as Modified but I have the same issue.

**Comment by vkarpov15** [comment]
Why not just use `doc.save()` in the `exec()` callback? `save()` is smart enough to do `update()` for you if its a document you loaded from the database.

**Comment by Persader** [comment]
I found a solution on stackoverflow : http://stackoverflow.com/questions/7267102/how-do-i-update-upsert-a-document-in-mongoose

delete model._id; // IMPORTANT
CraModel.update({userId: req.user.id, month: model.month, year: model.year}, model, {upsert: true}, function(err ) {
...
}

**Comment by vkarpov15** [comment]
Ah I see. This is related to #2065, but not quite identical. More recent versions of MongoDB don't allow you to update() a document's _id.
