### ISSUE TITLE
connection.readyState returns incorrect value when using auto_reconnect

### ISSUE THREAD

**Issue by ghost** [LearnBoost/mongoose#2656]
While testing error handling when connection drops I found that sometimes connection.readyState returns 1 event when MongoDB is down, in fact when this happens the 'disconnected' event is not emitted. After a while I found that this only happens when auto_reconnect is set to true, although this may happen after an arbitrary number of connection drops (sometimes 2, sometimes 10)

I was using this code while having this issue:
```javascript
mongoose.connection.on('disconnected', function() {
	console.log(chalk.red('Connection to MongoDB is down'))
})
mongoose.connection.on('error', function(err) {
	console.log(chalk.red(err))
	if(mongoose.connection.readyState) mongoose.connection.disconnect()
})
db = mongoose.connect(config.db)
```

Then I changed the code to:
```javascript
mongoose.connection.on('disconnected', function() {
	console.log(chalk.red('Connection to MongoDB is down'))
	setTimeout(function() {
		mongoose.connect(config.db,{server:{auto_reconnect:false,socketOption:{keepAlive:true}}})
	},2000)
})
mongoose.connection.on('error', function(err) {
	console.log(chalk.red(err))
	if(mongoose.connection.readyState) mongoose.connection.disconnect()
})
db = mongoose.connect(config.db,{server:{auto_reconnect:false,socketOption:{keepAlive:true}}})
```
And everything works as it should. I'm using Mongoose 3.8.21, Node 0.10.25, MongoDB 2.6.7
(I guess it's a driver issue)

**Comment by vkarpov15** [comment]
Hmm are you on OSX? I can't repro this on my linux mint box, but on OSX it seems to be losing an event handler somewhere.

**Comment by vkarpov15** [comment]
Waiting for mongodb@2.0.23 for this fix
