### ISSUE TITLE
$and modifier failed to work

### ISSUE THREAD

**Issue by leopoldfreeman** [LearnBoost/mongoose#2660]
I want to update one element in the array with multi conditions. I found the '$and' modifer failed to worked properly.

mongoose v3.8.23
mongodb v2.6.7

Here is my schema:
```javascript
var mailInfoSchema = new Schema({
    bodyId: String,
    read: Boolean
});

var mailSchema = new Schema({
    userId: String,
    mails: [mailInfoSchema]
});

var MailModel = db.model('Mail', mailSchema);

Mail.readMail = function (uid, mailId, cb) {
    MailModel.findOneAndUpdate(
        {"$and": [{userId: uid}, {'mails._id': mailId}, {'mails.read': false}]}, // '$and' doesn't work. But works in mongodb shell.
        {"$set": {mails.$.read: true}},
        {upsert: false, select: '_id'}, 
        cb
    );
};
```

Here is test data:
```javascript
db.mail.findOne();
{
	"_id" : ObjectId("54d8781ebd4f5e6080eb86eb"),
	"userId" : ObjectId("54d1c7ac78d4693c0ba2652c"),
	"mails" : [
		{
			"_id" : ObjectId("54d8781ef78fd0887e54c712"),
			"read" : false,
                        "bodyId": 1
		},
		{
			"_id" : ObjectId("54d8781f997aaf927e9b72be"),
			"read" : false,
			"bodyId" : "1"
		}
	],
	"__v" : 0
}
```

Call the function at the first time:
```javascript
Mail.readMail('54d1c7ac78d4693c0ba2652c', '54d8781ef78fd0887e54c712', cb);

> db.mail.findOne();
{
	"_id" : ObjectId("54d8781ebd4f5e6080eb86eb"),
	"userId" : ObjectId("54d1c7ac78d4693c0ba2652c"),
	"mails" : [
		{
			"_id" : ObjectId("54d8781ef78fd0887e54c712"),
			"read" : true, // Correct
			"bodyId" : "1"
		},
		{
			"_id" : ObjectId("54d8781f997aaf927e9b72be"),
			"read" : false,
			"bodyId" : "1"
		}
	],
	"__v" : 0
}
```

First time, works fine. Let's call again with the **same parameter**, it should not update any thing, but:
```javascript
Mail.readMail('54d1c7ac78d4693c0ba2652c', '54d8781ef78fd0887e54c712', cb);

> db.mail.findOne();
{
	"_id" : ObjectId("54d8781ebd4f5e6080eb86eb"),
	"userId" : ObjectId("54d1c7ac78d4693c0ba2652c"),
	"mails" : [
		{
			"_id" : ObjectId("54d8781ef78fd0887e54c712"),
			"read" : true,
			"bodyId" : "1"
		},
		{
			"_id" : ObjectId("54d8781f997aaf927e9b72be"),
			"read" : true,  // It updated this sub doc!!!
			"bodyId" : "1"
		}
	],
	"__v" : 0
}
```
Look at the second sub doc, the function updates the wrong doc.

**Comment by mcrisp** [comment]
I have been having and issue with $and operator as well.  When I run the same query within the mongo shell I get the correct answer, but when I pass it through the mongoose find() method I do not get the same result.  It seems to work depending on what is in the collection of add expressions.

Having said that...when I look at your code above I wonder if you are mixing up the mail and user id fields.

In your $and condition I see 
{'mails._id': mailId}
where mailId is passed to 
Mail.readMail = function (uid, mailId, cb) 

In your sample code you call this readMail method as follows

Mail.readMail(uid, '54d1c7ac78d4693c0ba2652c', cb);

I notice that id passed is a userid and not a mails._id in your sample data
{
    "_id" : ObjectId("54d8781ebd4f5e6080eb86eb"),
    "userId" : ObjectId("54d1c7ac78d4693c0ba2652c"),
    "mails" : [
        {

I did not look very closely so maybe I am missing something here...but just wondering if that is your issue.

Cheers
Martin Crisp

**Comment by leopoldfreeman** [comment]
You are right. It's a typo. This is not my issue. I copied some test codes from my project and typed some. Sorry.

**Comment by leopoldfreeman** [comment]
Just updated it. Thanks for point it out.

**Comment by vkarpov15** [comment]
The issue isn't with mongoose, it's more with how you're using the positional operator `$`. You get the same issue if you run `findAndModify` in the mongodb shell:

```
> db.gh2660.findAndModify({ query: { '$and': [ { userId: ObjectId("54d1c7ac78d4693c0ba2652c") }, { 'mails._id': ObjectId("54d8781ef78fd0887e54c712") }, { 'mails.read': false } ] }, update: { '$set': { 'mails.$.read': true } } });
{
	"_id" : ObjectId("54d8781ebd4f5e6080eb86eb"),
	"userId" : ObjectId("54d1c7ac78d4693c0ba2652c"),
	"mails" : [
		{
			"_id" : ObjectId("54d8781ef78fd0887e54c712"),
			"read" : true,
			"bodyId" : 1
		},
		{
			"_id" : ObjectId("54d8781f997aaf927e9b72be"),
			"read" : false,
			"bodyId" : "1"
		}
	],
	"__v" : 0
}
> db.gh2660.findOne()
{
	"_id" : ObjectId("54d8781ebd4f5e6080eb86eb"),
	"userId" : ObjectId("54d1c7ac78d4693c0ba2652c"),
	"mails" : [
		{
			"_id" : ObjectId("54d8781ef78fd0887e54c712"),
			"read" : true,
			"bodyId" : 1
		},
		{
			"_id" : ObjectId("54d8781f997aaf927e9b72be"),
			"read" : true,
			"bodyId" : "1"
		}
	],
	"__v" : 0
}
```

You'll want to [use the `$elemMatch` operator to match multiple fields for use with the positional operator](http://docs.mongodb.org/manual/reference/operator/update/positional/#update-embedded-documents-using-multiple-field-matches). The query you specified means "find me a document that has `mail._id = x`, has a subdoc in mails with `_id = y`, and has a (potentially different) mail subdoc with `read = false`. When you find that document, update its first unread mail to `read = true`." Whenever you want to an array element to match multiple criteria, you *must* use `$elemMatch`.

As a brief aside, you very rarely need to use `$and`. Usually, its only useful for [composing `$or` criteria](http://docs.mongodb.org/manual/reference/operator/query/and/#and-queries-with-multiple-expressions-specifying-the-same-operator) - in your case, it's entirely redundant and obfuscates the real issue.

The below implementation should work better for you:

```javascript
var readMail = function (uid, mailId, cb) {
    MailModel.findOneAndUpdate(
        { userId: uid, mails: { $elemMatch: { '_id': mailId, 'read': false } } },
        {"$set": {'mails.$.read': true}},
        {upsert: false },           
        cb
    );
};
```

As a matter of general schema design, you may want to consider not inlining every email in a single document. This will work well for when each user has a small number of mails, and so is good for experimenting, but once you start having users with hundreds of mails your documents will start to get very bloated and shipping huge documents over the network is bad for performance. You may even run into the 16MB document size limit. This is why it's generally bad practice to include arrays that grow without bound in MongoDB docs.

**Comment by leopoldfreeman** [comment]
Thanks for your explaination. By the way, it's a simple mail system for our game. Not a real Email system.
