### ISSUE TITLE
Why typeof ObjectId.valueOf() is 'object' and toString() returns hex string without ObjectId("xxx")

### ISSUE THREAD

**Issue by Fonger** [LearnBoost/mongoose#2663]
```js
var id = mongoose.Types.ObjectId();
console.log('Type of id.valueOf().....');
console.log(typeof id.valueOf())
console.log('');
console.log('Type of id.toString().....');
console.log(typeof id.toString())
console.log('');
console.log('Value of id.toString().....');
console.log(id.toString());
```
```
Type of id.valueOf().....
object

Type of id.toString().....
string

Value of id.toString().....
54da1871776bf123444364c7
```

However, according to [mongodb docs] (http://docs.mongodb.org/manual/reference/object-id/),
the above result only happens on legacy version (before 2.2).

`typeof id.valueOf()` should be `string` and the value is `54da1871776bf123444364c7` as string.
`id.toString()` should be `ObjectId("54da1871776bf123444364c7")` as string.

I'm using mongodb 2.6.7 and I'm confused by this.

**Comment by vkarpov15** [comment]
The [documentation you referenced](http://docs.mongodb.org/manual/reference/object-id/#core-object-id-class) refers specifically to the mongodb shell. Mongoose is an entirely separate project aimed at a different use case. The underlying BSON is identical, but mongoose's wrapper around ObjectIds is geared towards web development, whereas the shell is typically used for debugging, experimentation, and ops-type maintenance tasks.
