### ISSUE TITLE
Handling errors in async validation

### ISSUE THREAD

**Issue by paglias** [LearnBoost/mongoose#2674]
I have an async validation that runs a query against a model. If that query results in an error, what should I do?

If I throw it, it throws out node, it seems (#2185)

If I pass it to `done` it's treated as `true`. I'm using koa, wrapping all the requests in a try catch block but it doesn't seem to catch it.

So I'm not sure how I should behave, actually I'm returning `false`, treating it as a validation error that at least block the model from being saved but I would like to pass the error to my main error handler (try-catch block). 

There is a way to make it bubble up to the `.validate()` or `.save()` methods?

**Comment by paglias** [comment]
As a solution I propose to allow an error to be passed to `done` or change its signatute to `done(err, result)` which i think is the standard way to handle callback

I'm on 4.0.0-rc2

**Comment by vkarpov15** [comment]
Custom validators have this one little gotcha: the callback function signature is:

```javascript
function(ok) {}
```

So you pass it "false" if there's no error and "true" if there's an error. So `callback(true)` is really the only way to communicate that there was a validation error, mongoose will then create a new error for you that's the validation error. It also treats "undefined" as true. Its a little non-standard, and I'll think about tweaking it for the next major release.

If you really want to populate the exact query error, I'd recommend using a `pre('validate')` hook (or a `post('validate')` hook, depending on whats right for your use case)

**Comment by paglias** [comment]
>So you pass it "false" if there's no error and "true" if there's an error. 

I think it's the oppsite, at least this is how it's working for me and explained in the docs (http://mongoosejs.com/docs/api.html#schematype_SchemaType-validate)

>The second argument is a callback function that must called when you finish validating the value and passed either true or false to communicate either success or failure respectively.


>If you really want to populate the exact query error, I'd recommend using a pre('validate') hook (or a post('validate') hook, depending on whats right for your use case)

Could you please make an example?

As for the tweak, it's going to be for v5 or it can still make it in v4?

The main problem is that if I set it as a validation error error while it was a different error which i might want to treat in a different way it's really impossible to tweak the response according to it because it will be exactly the same as a normal validation error occurred

**Comment by vkarpov15** [comment]
I think this will have to be just something that's documented for v4 - much of the point of validators is that you simply define an error message in your schema rather than having to manually construct one yourself.

Try:

```javascript
schema.pre('validate', function(next) {
  OtherModel.findOne(query, function(error, doc) {
    if (error) {
      return next(error);
    }
    // Do stuff with doc
  });
});
```

If there's an error, `validate()` will call back with an error that's the error from the query.
