### ISSUE TITLE
_id in populated object is a string not ObjectId

### ISSUE THREAD

**Issue by uptownhr** [LearnBoost/mongoose#2677]
When using population, the returned intances _id is a string instead of a ObjectId. This causes errors when doing == comparison between two instances against the id. 

STR
1. Create a population schema
2. Get instance 1
3. Get instance 2, with population that includes instance 1
4. instance2._id == instance1._id is false
5. however, instance2._id == instance1._id.toString() is true

**Comment by vkarpov15** [comment]
It is an object id, just using `==` makes JavaScript try to coerce `instance2._id` into a string. `instance2._id === instance1._id.toString()` will be false. I'd recommend using `===` except for cases when you really want type coercion.

Also, `instance1._id == instance2._id` being false is expected. ObjectIds are objects, so `==` will only return true if they're the exact same object. When you populate, mongoose creates a new ObjectId object with the same hex string representation, so equality check will be false. If you want to compare two ObjectIds for equality, you should either convert both to strings with `toString()` or use deep equality comparisons like underscore's or lodash's.

**Comment by uptownhr** [comment]
I still dont understand how step 5 is true then.

**Comment by vkarpov15** [comment]
For the same reason that `{} == '[object Object]'` in JavaScript. The `==` operator does type coercion, so when the right side is a string, `==` will check if the left side has a `toString()` function, and, if `lhs.toString()` returns a primitive, use that value for comparison. See [section 11.9.3](http://www.ecma-international.org/ecma-262/5.1/#sec-11.9.3) and [section 8.12.8](http://www.ecma-international.org/ecma-262/5.1/#sec-8.12.8) of the ECMAScript 5.1 spec. Basically, `==` can give you some unexpected behavior, and there's almost always no reason to use it. Better to be explicit and use `===`.

**Comment by uptownhr** [comment]
Thanks. Learned something new today
