### ISSUE TITLE
Manually populated field `populated` returns object not _id (3.9)

### ISSUE THREAD

**Issue by whitecolor** [LearnBoost/mongoose#2678]
Considering https://github.com/LearnBoost/mongoose/issues/2370 it seems that it is correct usage of mongoose to manually populate field (direclty assign objectId field with corresponding object).

According to  http://mongoosejs.com/docs/api.html#document_Document-populated
`pupulated` should return `_id` of object

But when field is populated (assigned) manually `populated` returns object instance itself on its `_id`

```javascript
var childrenSchema = new Schema({ name: String});

var parentSchema = new Schema({ 
    name: String,
    child: { type: Schema.Types.ObjectId, ref: 'Child'}
});

var Parent = mongoose.model('Parent', parentSchema, 'parents');
var Child = mongoose.model('Child', parentSchema, 'children');

var child = new Child({ name: 'Mary' });
var parent = new Parent({ name: 'Alex', child: child });

console.log(parent.populated('child')); //-> outputs child object, not its _id
```

**Comment by shadow0162** [comment]
In that case, i have other question.After saved doc to db,what is type of child in parent doc?embed doc or ObjectID?

**Comment by whitecolor** [comment]
It saved as `_id` in DB, not object.
