### ISSUE TITLE
How can I force the query to return error so I can test the code?

### ISSUE THREAD

**Issue by airyland** [LearnBoost/mongoose#2680]

**Comment by vkarpov15** [comment]
Can you clarify what you mean? I'm not sure I understand your question.

**Comment by airyland** [comment]
Sorry, I mean how I can force mongoose to return errors for unit testing:

```javascript
Model.find({}).exec(function(err,data){
   if(err){
    // I cannot trigger the err, so I cannot test this logic.
   }else{
    // I can test it.
  }
});
```

**Comment by vkarpov15** [comment]
The right way would be to create a stubbed out version of Model - you should be doing this if you're writing true unit tests as opposed to integration tests. I'm actually working on a module to help with creating stubbed out objects at the moment :) People also use [sinon](https://www.npmjs.com/package/sinon) for this purpose, but I'm not a big fan.

The quick-and-dirty hack would be to overwrite Model.exec in your test code if you don't want to write proper unit tests.

```javascript
// test code
Model.exec = function(callback) {
  process.nextTick(function() {
    callback(new Error('this is an error'));
  });
};
```

**Comment by airyland** [comment]
THX
