### ISSUE TITLE
There is a comment Error in master branch ./lib/index.js

### ISSUE THREAD

**Issue by LightTao** [LearnBoost/mongoose#2681]
@rauchg 

I find [This Line](There is a comment Error in master branch ./lib/index.js)
![screen shot 2015-02-15 at 4 00 35 pm](https://cloud.githubusercontent.com/assets/988193/6202527/d4aecc84-b52b-11e4-994a-9a65b52f967b.png)

But the file named schemadefault.js is removed

**Comment by vkarpov15** [comment]
Thanks for pointing this out. That file only stored setProfiling, which was removed for 4.0 (not a particularly useful API)
