### ISSUE TITLE
PoolSize requires a parseInt if using process.env

### ISSUE THREAD

**Issue by thedug** [LearnBoost/mongoose#2682]
I'm pull my config from process.env, if I set poolSize without parseIn Mongoose will not connect to the connection pool and then queries will just silently hang.

The hangs 
```javascript
options: {
    user: process.env.DB_USER || '',
    pass: process.env.DB_PASS || '',
    server: { poolSize: process.env.DB_POOL_SIZE || 5 }
}
```

This works fine
```javascript
options: {
    user: process.env.DB_USER || '',
    pass: process.env.DB_PASS || '',
    server: { poolSize: parseInt(process.env.DB_POOL_SIZE, 10) || 5 }
}
```

**Comment by mathieumg** [comment]
All environment variables are strings. I don't see how that is a problem here since you already applied the correct solution.

**Comment by thedug** [comment]
The problem is that it is unexpected for a dynamic language to care about type, especially on a simple confit value.

Very easy to accept a string or at least warn the user.

**Comment by vkarpov15** [comment]
You're right, silently hanging is bad.

**Comment by vkarpov15** [comment]
PR was merged, but will have to wait for node driver v1.4.32

**Comment by fernan256** [comment]
Hi, little bit old question, but just to be sure, I can use pool Size with process.env.VAR without troubles? or should I use the parseInt option?

**Comment by vkarpov15** [comment]
Yes you should be able to. If you find that string poolSize doesn't work, please open up a separate issue with code samples
