### ISSUE TITLE
populate repeats id's in query

### ISSUE THREAD

**Issue by guymguym** [LearnBoost/mongoose#2683]
I turned on debug on mongoose and noticed that a find query with multiple results which does populate will send a populate query to mongo with many repeating ids. 

It would be better to first make the list unique before sending out, and then use the same referenced document for populating the referring doc path. This would also be correct from the "sql-join" perspective as the referenced document is the same one.

details:

this is with mongoose version 3.8.22.
my schema is using a simple ref, something like in the populate example but with ObjectId:

```javascript
var mongoose = require('mongoose')
  , Schema = mongoose.Schema
  
var personSchema = Schema({
  name    : String,
});

var storySchema = Schema({
  genre    : String,
  creator : { type: Schema.Types.ObjectId, ref: 'Person' },
});

var Person = mongoose.model('Person', personSchema);
var Story  = mongoose.model('Story', storySchema);
```

The query is returning multiple Stories and populates their creator:

```javascript
Story.find({genre: /fantasy/}).populate('creator')
```

and the sample from debug log is (in the above example J.R.R Tolkien's id will repeat several times)

```
Mongoose: persons.find({ _id: { '$in': [ ObjectId("54d8be49b60318713e92f014"), ObjectId("54d8be49b60318713e92f010"), ObjectId("54d8be49b60318713e92f011"), ObjectId("54d8be49b60318713e92f012"), ObjectId("54d8be49b60318713e92f013"), ObjectId("54d8be49b60318713e92f014"), ObjectId("54d8be49b60318713e92f014"), ObjectId("54d8be49b60318713e92f012"), ObjectId("54d8be49b60318713e92f013"), ObjectId("54d8be49b60318713e92f010"), ObjectId("54d8be49b60318713e92f011"), ObjectId("54d8be49b60318713e92f014"), ObjectId("54d8be49b60318713e92f012"), ObjectId("54d8be49b60318713e92f013"), ObjectId("54d8be49b60318713e92f010"), ObjectId("54d8be49b60318713e92f011"), ObjectId("54d8be49b60318713e92f014"), ObjectId("54d8be49b60318713e92f012"), ObjectId("54d8be49b60318713e92f013"), ObjectId("54d8be49b60318713e92f010"), ObjectId("54d8be49b60318713e92f011"), ObjectId("54d8be49b60318713e92f014"), ObjectId("54d8be49b60318713e92f012"), ObjectId("54d8be49b60318713e92f013"), ObjectId("54d8be49b60318713e92f010"), ObjectId("54d8be49b60318713e92f011"), ObjectId("54d8be49b60318713e92f014"), ... ] } }) { fields: undefined }  
```

**Comment by vkarpov15** [comment]
I don't necessarily think the same referenced document is a good approach, but I do agree that making the list unique is a good idea.

**Comment by guymguym** [comment]
@vkarpov15 Great! Your comment made me realize that it might be confusing to link to the same referenced document unless explicitly desired by the application. 

In many of my case this is actually making a lot of sense because I only want the populated document to fetch query data, and not to use as a real fully-featured document.

Can this case be opt-in with a populate option? maybe something like "dedupDocs"?

**Comment by vkarpov15** [comment]
I'm not sure I understand your use case. Can you tell me more about what you're trying to do?

**Comment by guymguym** [comment]
sure, in one case I have a file-system-like structures with files and folders as mongo documents.
a file refers to its parent folder (also folders do so).
when I query the files I populate the parent to get it's name and other attributes to return to my front-end.
this case is repeating in more relations.
in this case it would be great to just get a folder document once per all the files that have the same parent in the query.
makes sense?

**Comment by guymguym** [comment]
:+1:

**Comment by vkarpov15** [comment]
Fair warning, will only work for ObjectIds, strings, and numbers for now. Won't bother with deep equality checks for objects unless somebody really wants it, so you will still get dups if your _id is an object. On the other hand, there are probably other bugs inherent to having object _ids in mongoose, so probably not a big concern :)
