### ISSUE TITLE
TypeError 'length' of undefined using mongodb 3

### ISSUE THREAD

**Issue by kahwooi** [LearnBoost/mongoose#2684]
I am trying to use mongoose 3.8.21 with new mongodb 3:

I get this when is connected to the database:

```
TypeError: Cannot read property 'length' of undefined
   at processResults (E:\project\node_modules\mongoose\node_mo
ules\mongodb\lib\mongodb\db.js:1581:31)
   at E:\project\node_modules\mongoose\node_modules\mongodb\li
\mongodb\db.js:1619:20
```

**Comment by mathieumg** [comment]
I'm not 100% sure about this, but you might need to use Mongoose 4 RC for MongoDB 3 support.

**Comment by vkarpov15** [comment]
Upgrade to 3.8.23. 3.8.22 introduced better compatibility with mongodb server 3.0 by upgrading to latest version of the driver.
