### ISSUE TITLE
findByIdAndUpdate does not work

### ISSUE THREAD

**Issue by AleksMx** [LearnBoost/mongoose#2687]
Hello, we use this code:
var obj = {};
obj ['nextID'] = 1;
....findByIdAndUpdate (ID, { '$inc': obj }, {'new': true, 'upsert': true, 'select': obj}, callback);

It is work fine with 3.8.12 version, but in the version 3.8.23 we get this error "MongoError: exception: You cannot currently mix including and excluding fields. Contact us if this is an issue.". It think it is bug,,

**Comment by vkarpov15** [comment]
The issue is with [this commit](https://github.com/LearnBoost/mongoose/commit/196eba726fda87c1a5c7816e9f3ed2cda03c1ec2). Since options.select is the same object as $inc, changes to $inc are changes to select.
