### ISSUE TITLE
bson 'MODULE_NOT_FOUND"

### ISSUE THREAD

**Issue by CrackerakiUA** [LearnBoost/mongoose#2705]
With the new update of nodejs mongoose throw error in which it cant find module bson. perhaps nodejs tha added this module to they library, so you need to remove it from the code. I am using latest "*" version of mongoose, do i need to download development version?

**Comment by vkarpov15** [comment]
So mongodb can't find the bson module? That's strange. Are there any errors when you run npm install? Have you cleared your node_modules and re-run npm install after upgrading to node 0.12?

**Comment by CrackerakiUA** [comment]
yeah i have this on new projects and on old projects. No error detected on npm install

**Comment by vkarpov15** [comment]
You're running Windows I presume? What version?

**Comment by CrackerakiUA** [comment]
Have it on windows 7 64, windows 7 32, windows 8 64 and windows xp :)

2015-02-23 22:35 GMT+02:00 Valeri Karpov <notifications@github.com>:

**Comment by vkarpov15** [comment]
I'll give this a shot on my windows box :)

**Comment by CrackerakiUA** [comment]
notice that it need new install of nodejs, i have old one and it's working
normally

2015-02-24 18:51 GMT+02:00 Valeri Karpov <notifications@github.com>:

**Comment by vkarpov15** [comment]
What do you mean? I don't think I understand your latest comment.

**Comment by CrackerakiUA** [comment]
i have installed nodejs on windows like 1 year ago and it's working. All
new installs have that problem. As i see it, nodejs in latest version have
bson on it's own library and tell to mongoose to dont load it, but mongoose
in code still asking bson and asking it from wrong path.
{ [Error: Cannot find module '../build/Release/bson'] code:
"MODULE_NOT_FOUND"}

2015-02-24 21:33 GMT+02:00 Valeri Karpov <notifications@github.com>:

**Comment by ericmdantas** [comment]
I've got the same problem (Windows user too).

The problem is in:

```
myAppPath\node_modules\mongoose\node_modules\mongodb\node_modules\bson\ext\index.js
```

Where it tries to import from:

```js
bson = require('../build/Release/bson');  
```

But such folders don't exist.

**Comment by vkarpov15** [comment]
Yeah looking into it, this isn't an error. Its a warning that says you can't compile bson, so you probably don't have [the proper node-gyp dependencies installed](https://github.com/TooTallNate/node-gyp#installation). Mongoose will still work as expected even if the bson compilation fails, you should see the "js-bson: Failed to load c++ bson extension, using pure JS version" warning right after the module not found warning.

The only exception is that Mongoose only supports [Kerberos auth](http://en.wikipedia.org/wiki/Kerberos_%28protocol%29) through a native add-on, but if you're the kind of person that cares about kerberos I'd expect you'd have a C++ compiler on your machine anyway :)

FWIW I'm not a big fan of node-gyp and its global state and arcane setup process, but no better solution exists ATM for compiling nodejs native add-ons. Your code will still work in development, but I'd recommend you have python+gcc (or VS for windows) in your prod environment.
