### ISSUE TITLE
"increment" should be a reserved path

### ISSUE THREAD

**Issue by chazmo03** [LearnBoost/mongoose#2709]
If a document has a field named "increment", it conflicts with the increment() method called in model.js. This should either be fixed or "increment" should be added to the reserved paths list.

**Comment by vkarpov15** [comment]
Yeah this is a bit of a problem - I don't want to add it to reserved keywords, because if versioning is off then its perfectly fine to have a key named `increment` as far as I know. I suppose I can add a warning for this though.

**Comment by chazmo03** [comment]
Thank you for addressing this. A warning would also do the trick I suppose.
