### ISSUE TITLE
type keyword in nested object 

### ISSUE THREAD

**Issue by melbourne2991** [LearnBoost/mongoose#2710]
I noticed that if I have a nested object like so

myschema({
  someProperty: Number,
  type: Number
});

Mongoose interprets the nested object itself to be of type number, therefore throwing errors when trying to set anything on it later.

For others with this problem, it can be solved by doing this:

type: {type: Number}

Fair enough if it's a reserved keyword, but there should probably be a more descriptive error/warning that let's the user know this. You could look to see if other non mongoose properties have been set on the object to determine if their intention was for the object to be used as a type caster or as an actual object that's part of the schema.

**Comment by vkarpov15** [comment]
Could make sense to make a warning if you have a top-level field called "type", because you wouldn't save a doc that's just a number, but if its nested there's really no way to tell.
