### ISSUE TITLE
Does chaining query.where() method add any operator to our query like $and operator

### ISSUE THREAD

**Issue by efkan** [LearnBoost/mongoose#2721]
Hello,

I was wondering that does chaining query.where method inserts any operator when we use second or third time sequentially like the following;

    var query = modelUser.find();
    query
    .where('firstname')
    .equals('John')
    .where('lastname')
    .equals('Abbott')
    
Which one is the right answer the following matters for the above case?

1- The above query run on MongoDB like this;
     `db.collection('user').find({ firstname: 'John', lastname: 'Abbott' })`

2- The above query run on MongoDB like this;
    `db.collection('user').find({ $and: [{ firstname: 'John' }, { lastname: 'Abbott' }] })`

**Comment by vkarpov15** [comment]
Case 1 is what will actually get sent.

For future reference, if you want to know what queries and writes mongoose is sending to the server, use `require('mongoose').set('debug', true);` . You should see some nice handy debug output that shows the actual queries and such.

**Comment by efkan** [comment]
Yes.. Debug parameter. 
Thanks..
