### ISSUE TITLE
`Model.find` Array of ObjectId's not returning any results

### ISSUE THREAD

**Issue by MadLittleMods** [LearnBoost/mongoose#2728]
The following barebones snippet should return any documents that has the userId in their array of ObjectId's,  but instead returns nothing.

Mongoose version 3.8.23

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var ObjectId = Schema.ObjectId;

// Connect to the database
mongoose.connect('mongodb://127.0.0.1:27017/mydb');

var QueueSchema = new Schema({
	userIds: {
		type: [ObjectId],
		required: true
	}
});

var Queue = mongoose.model('Queue', QueueSchema);

/* * /
// Add a test queue to the collection to use
var queue = new Queue();
queue.userIds = [new require('mongoose').Types.ObjectId('54effc576676066c20293010')];
queue.save(function(err) {
	if(err) {
		console.log(err);
	}
});
/* */




// NOTE: In the Mongo shell, this works: db.queues.find({userIds: ObjectId('54effc576676066c20293010')})
var myQuery = Queue.find({
	usersIds: '54effc576676066c20293010'
	//usersIds: new require('mongoose').Types.ObjectId('54effc576676066c20293010')
}).exec();

myQuery.then(function(docs) {
	console.log('d', docs);
}, function(err) {
	console.log('Err', err);
});
```

**Comment by dauvray** [comment]
Same problem ... very blocking, thanks

**Comment by vkarpov15** [comment]
OP's example is due to a typo:

```javascript
var myQuery = Queue.find({
    usersIds: '54effc576676066c20293010'
}).exec();
```

Should be:

```javascript
var myQuery = Queue.find({
    userIds: '54effc576676066c20293010'
}).exec();
```

Note that "userIds" field is misspelled "usersIds" with an extra s in the original example. Since the field is not in the schema, mongoose doesn't know to cast it to an objectid.

@dauvray perhaps you have a similar issue? Can you provide a similar example reproducing the bad behavior you're seeing?

**Comment by MadLittleMods** [comment]
@vkarpov15 Thanks, silly mistake on my part. I ended up making a new collection for the userId's and permissions which is a better setup anyway.

**Comment by vkarpov15** [comment]
No worries. Took me a solid 20 minutes or so to catch that typo - these sort of bugs are really difficult to catch. And depending on your use case that may or may not be better architecture. Don't hesitate to reach out if you have questions about schema design :)

**Comment by dauvray** [comment]
```javascript
 Card.find(
            {packId: packId },
            function(err,cards){
                if(err){
                    console.log(err);
                }else{
                    console.log(cards);
                }
            }
        );
```
i'm using this code. ( it works with other models) but here , console.log(cards) returns empty array.
If i replace {packId: packId },  with a static value {packId: '55083c370e5fcc8e1ea7984c' }, it works.
 i precise i'm on the good database, packid is a objectId  and when i do the querry in mogo, it works.

But i saw a difference in the mongoose/lib/model.js : if i console.log(conditions) at the end of Model.find function i 've got

- { packId: '55083c370e5fcc8e1ea7984c' }  in the case of static value => return results
- { packId: 55083c370e5fcc8e1ea7984c } in the case of objectId => empty array

Maybe something wrong with my code but i don't understand ...

**Comment by vkarpov15** [comment]
Well if the static value works, the question is, what is `packId`? Try logging it and seeing what happens.

**Comment by dauvray** [comment]
It's a good question ... when i console.log(packId) => 55083c370e5fcc8e1ea7984c and console.log(typeof packId) => object ...  i don't know anything more.

And packId come from a callback
```javascript
pack.save(function(err, pack){
            if(err){
                console.log("createPack : "+ err);
            }else{
                callback(pack._id);
            }
        });
```

Where is my mistake please ...

Thanks

**Comment by vkarpov15** [comment]
Try doing `Card.find({ packId: packId.toString() });` packId might be some sort of weird object that mongoose isn't quite able to convert into an objectid.

**Comment by dauvray** [comment]
this is the first thing I did because of course I read all possible
forums and applied all the solutions. For me there is a problem
mongoose ...


2015-03-18 14:42 GMT+01:00 Valeri Karpov <notifications@github.com>:

**Comment by dauvray** [comment]
this is the first thing I did because of course I read all possible forums and applied all the solutions. For me there is a problem mongoose ...

**Comment by dauvray** [comment]
it's crazy ... don't works ... of course i've read all forums before post here ...

**Comment by vkarpov15** [comment]
What does your card schema look like?

**Comment by dauvray** [comment]
I think i find an issue . this is a part of my code

```javascript
models.Card.saveCards(completeData.cards,packData.cid, function(){
    models.Card.getCards(packData.cid,function(cards){
    ...
    }
}
```
I think the second method getCards is called before all cards are saved. is it possible ?
