### ISSUE TITLE
CastError when populating schema with reference saved as {}

### ISSUE THREAD

**Issue by aaunel** [LearnBoost/mongoose#2729]
`Population: CastError: Cast to ObjectId failed for value “[object Object]” at path “_id”`

Running into a `CastError` in Mongoose when populating nested ObjectId references (value `{}`) that are apparently _valid_, to the extent that they're not blocked when saving to schema.

Interested in resolving this on the server-side to prevent malformed data in future, however, I understand not saving these values from the client would be a good idea. The fact that an empty object _can_ be saved to a Mongoose schema with `type: mongoose.Schema.Types.ObjectId` and later throws a `CastError` using population is my primary concern.

Originated from [StackOverflow](http://stackoverflow.com/questions/28705810/mongoose-population-casterror-cast-to-objectid-failed-for-value-object-objec)

**Comment by vkarpov15** [comment]
Hmm actually @aaunel, as far as I can tell, mongoose is failing to save `{}`. The CastError is happening when you call `create()` in the test case, not when you call `findById`, which is what I'd expect: `{}` is not a valid ObjectId. In other words, I'm not sure how you managed to save `{}` in an ObjectId field, mongoose doesn't allow that. Can you verify that this is the behavior you're seeing?

**Comment by aaunel** [comment]
I've replicated the issue with test cases (and now fixed) in the pull request referenced above PR #2732
