### ISSUE TITLE
A particular feature in mongoose... (related to find and $in)

### ISSUE THREAD

**Issue by Gionni** [LearnBoost/mongoose#2731]
Hi guys, anyone knows a mongoose feature I could use for extracting N sentences from my collection but proportionally to the number of languages I got inside e.g. N/3 for "en", N/3 for "de", N/3 for "fr".

Sentence.find({ language: { "$in" : ["en", "de", "fr"] } })
      .nin('_id', filterOut)
      .limit(N)
      .select({ ... })
      .exec(function(err, sentences) {
               ...
});

I'd really appreciate it

**Comment by vkarpov15** [comment]
Not that I know of, I think you would just need to make 3 queries with limit N/3

**Comment by Gionni** [comment]
Late, sorry, I've been sick this week. 
Being the languages array arbitrary (depending upon...), if I make multiple queries in cascade I got the callbacks hell with the problem to "union" the results. Have I to use Promise for this?
Thanks a lot

**Comment by vkarpov15** [comment]
`async.parallel()`, see [the async module on npm](https://www.npmjs.com/package/async).
