### ISSUE TITLE
runValidators = true causes TypeError: Object #<Object> has no method 'validate' with subdocuments

### ISSUE THREAD

**Issue by rodriguise** [LearnBoost/mongoose#2733]
My schema is similar to below, the db.x returns a mongoose-validator instance. I have tried the following in both 3.9.7 and master.

    var ApplicationCallbackSchema = db.defineSchema({
        url: { type: String, required: true, validate: db.urlValidator('url') },
        events: { type: [String] }
    } );

    var ApplicationSchema = db.defineSchema({
        name: { type: String, required: true, index: true, unique: true, validate: db.stringLengthValidator('name', 8, 32) },
        transports: [Transport],
        callbacks: [ApplicationCallbackSchema]
});

This call:

     model.findOneAndUpdate({ _id: req.params.id }, req.body, { new: true, runValidators: true }...

Results in:

    TypeError: Object #<Object> has no method 'validate'
        at /Volumes/Workspace/qwasi/current/current/mojo-engine/node_modules/mongoose/lib/schema/documentarray.js:100:13
        at /Volumes/Workspace/qwasi/current/current/mojo-engine/node_modules/mongoose/lib/schema/documentarray.js:106:9
        at DocumentArray.SchemaType.doValidate (/Volumes/Workspace/qwasi/current/current/mojo-engine/node_modules/mongoose/lib/schematype.js:647:22)
        at DocumentArray.doValidate (/Volumes/Workspace/qwasi/current/current/mojo-engine/node_modules/mongoose/lib/schema/documentarray.js:79:35)
        at /Volumes/Workspace/qwasi/current/current/mojo-engine/node_modules/mongoose/lib/services/updateValidators.js:87:33
        at /Volumes/Workspace/qwasi/current/current/mojo-engine/node_modules/async/lib/async.js:570:21
        at /Volumes/Workspace/qwasi/current/current/mojo-engine/node_modules/async/lib/async.js:249:17
        at /Volumes/Workspace/qwasi/current/current/mojo-engine/node_modules/async/lib/async.js:125:13
        at Array.forEach (native)
        at _each (/Volumes/Workspace/qwasi/current/current/mojo-engine/node_modules/async/lib/async.js:46:24)

Any assistance is much appreciated.

**Comment by vkarpov15** [comment]
Can you show me what the code that generates your validators looks like?

**Comment by rodriguise** [comment]
var urlValidator = function(name) {
        return
	    validate({
	        validator: 'isURL',
                arguments: { protocols: ['http', 'https'], require_protocol: true },
	        message: util.format('URL \'%s\' must be a valid http or https url.', name),
	        type: 'BadUrl'
	    });
    };

**Comment by vkarpov15** [comment]
Confirmed, document arrays and update validators don't work well together :(

**Comment by rodriguise** [comment]
I create a gist that has a decent work around in the meantime using the standard validation. This allows for validation and to still use the atomic update operations safely.

https://gist.github.com/rodriguise/5b258dba14ba49bf0087

**Comment by AkashDelhi** [comment]
Is the fix of this issue part of 4.0.1 ?

**Comment by vkarpov15** [comment]
The issue is you're using a key named "type" in `offlineView`. That's telling mongoose that offlineView has type object, and so is equivalent to:

```javascript
new Schema({
  offlineView: Mixed
});
```

So with the current schema, no validation is done for anything under offlineView, whether using update validators or not. Rename the "type" key to "kind" or something similar and it should work.

**Comment by AkashDelhi** [comment]
Thanks @vkarpov15 for making me learn more about mongoose :)
