### ISSUE TITLE
Slice / Projection with Mongoose

### ISSUE THREAD

**Issue by nottinhill** [LearnBoost/mongoose#2736]
I have a huge array with hundreds of thousands of objects in my Big Data application stored in MongoDB. Now when I request the data I want to limit the returned array to the first 100 elements. 

Currently due to the lack of better knowledge I am fetching the whole array and then slicing the array in my router like so:

     return Domain.find({domain:req.params.domain})
     .where('date').equals(date)
     .exec(function (err, domain) {
        if (!err) {
          if (!isEmpty(domain[0].visitors)) {
            domain[0]['visitors'] = domain[0].visitors.slice(0,99);
          }
      }

It should be unnecessary to mention that performance is far from ideal when doing it like this. How would you limit this request from MongoDB with Mongoose natively?

I am also trying to use the node.js Mongodb connector, but stil fails due to some warnings.

    // Fallback to MongoDRM node.js native driver 
    //
    return Domain.collection.find(
    
      { "domain":req.params.domain }, 
      { "date":date }, 
      { "visitors": { $slice:100 } }, 
      function(err,domain){
         ...

but I am getting this

**Error**: `TypeError: Converting circular structure to JSON`
**Full code**: https://gist.github.com/nottinhill/b3837d4c913b9e5dd879

**Comment by nottinhill** [comment]
I am now trying to use the node.js Mongodb connector, but stil fails due to some warnings.


    // Fallback to MongoDRM node.js native driver 
    //
    return Domain.collection.find(
    
      { "domain":req.params.domain }, 
      { "date":date }, 
      { "visitors": { $slice:100 } }, 
      function(err,domain){
         ...

but I am getting: 

`TypeError: Converting circular structure to JSON`

**Comment by nottinhill** [comment]
Works:

    return Domain.find({domain:req.params.domain})
      .where('date').equals(date)
      .slice ('visitors', 5)

So to sum it up. You define the array in the Mongoose `slice` method. No need for using native MongoDB driver - why it fails with above error remains interesting.

**Comment by vkarpov15** [comment]
Yep you can just use the slice() helper. You can do the same thing with the driver with a projection:

```javascript
Domain.collection.find({ domain: req.params.domain, date: date }, { visitors: { $slice: 100 } }).toArray(function(err, docs) {
  // Docs is a list of objects
});
```
