### ISSUE TITLE
Mongoose 4 RC and mongo-connect error

### ISSUE THREAD

**Issue by whitecolor** [LearnBoost/mongoose#2739]
Here is an error that happens with `mongoose 4rc-3` and `connect-mongo 0.4.1`
https://gist.github.com/whitecolor/877afbce9bdc9bb2bba2

**Comment by whitecolor** [comment]
closed. old version of connnect-mongo was used.

**Comment by vkarpov15** [comment]
For future reference, I'd recommend using [connect-mongodb-session](https://www.npmjs.com/package/connect-mongodb-session) instead. connect-mongo is no longer maintained and has several known issues.
