### ISSUE TITLE
connecting event is not emitted 

### ISSUE THREAD

**Issue by alcor93** [LearnBoost/mongoose#2753]
"connecting" event which should be emitted when connection.{open,openSet}() is executed on the connection seems to not work

**Comment by vkarpov15** [comment]
Can you clarify which version of mongoose you're using?

**Comment by alcor93** [comment]
last stable version 3.8.24 and the latest version 4.0.0

2015-03-11 18:56 GMT+01:00 Valeri Karpov <notifications@github.com>:

**Comment by vkarpov15** [comment]
Hmm can you provide me a standalone example that shows how you're using this? We have tests covering the `connecting` event getting emitted properly...

**Comment by alcor93** [comment]
ok, I got it!
actually my event was written after the opening of the connection.
If I write the event before the connection.{open,openSet}, it works.
Sorry,
thanks

2015-03-12 17:55 GMT+01:00 Valeri Karpov <notifications@github.com>:

**Comment by vkarpov15** [comment]
Yeah that event gets emitted synchronously, somewhat confusing, but no real need to wrap it in a nextTick() IMO
