### ISSUE TITLE
Storing a geo polygon

### ISSUE THREAD

**Issue by thebergamo** [LearnBoost/mongoose#2764]
Hello guys!

I need store on my MongoDB and query a Polygon area of my map.

I need a document like this:

https://gist.github.com/marcosbergamo/7e557656adf419fc1537

How I can do this?

**Comment by vkarpov15** [comment]
```javascript
new mongoose.Schema({
  bounds: {
    geo: {
      type: { type: String },
      coordinates: [Array]
    }
  },
  zoom: Number
});
```

Should work

**Comment by thebergamo** [comment]
Well, on my case I use Mixed, because I need storing a multidimensional array.

Thanks @vkarpov15 for your reply =D

**Comment by ntk860** [comment]
I am trying to do exactly the same, I am getting an error saying 'Point must only contain numeric elements'

**Comment by vkarpov15** [comment]
@ntk860 please provide code samples and stack trace.
