### ISSUE TITLE
CastError when creating document using new with invalid ObjectId but setting it before saving.

### ISSUE THREAD

**Issue by amsterdamharu** [LearnBoost/mongoose#2766]
http://stackoverflow.com/questions/29090704/mongoose-cast-to-objectid-failed-for-value-on-newly-created-object-after-settin?noredirect=1#comment46413741_29090704

Using 3.8.17

Let's say the schema says it should be an ObjectId (In the example I have it reference another collection but for the test it can be any ObjectId)

    var serviceSchema = paramMongoose.Schema({
      serviceName:{ 
       type: paramMongoose.Schema.Types.ObjectId
       , ref: 'servicenames',required:true 
      }
    });

pseudo code:

    serviceFromDB=new Service({serviceName:'some Name'});
    serviceFromDB.serviceName='000000000000000000000001';
    serviceFromDB.save(function(paramError,paramData){
      if(paramError){
        console.log('but but but...',serviceFromDB,paramError)
      }
    });

The output of this code is:

> but but but... { serviceName: 000000000000000000000001,
> _id: 55079a90286f49280364f78b } { [CastError: Cast to ObjectId failed for value "some Name" at path "serviceName"]

So even though the current value of serviceName is valid (castable to ObjectId), the save function seems to be using the value set when serviceFromDB was created (constructor passed value).

**Comment by vkarpov15** [comment]
So in theory this was fixed in master, but apparently wasn't. Put in a PR to change that. This change will not be backported to 3.8.x, but will be in 4.0.0

**Comment by amsterdamharu** [comment]
Even though I sometimes curse every line of code in mongoose out of frustration you people do do a great job. Many thanks for your quick response and please let me know if there is something I can do to help.

**Comment by vkarpov15** [comment]
Yeah I must confess that I occasionally have those moments too :) Working towards the day that those moments don't happen.
