### ISSUE TITLE
Why are not all of the BSON data types supported?

### ISSUE THREAD

**Issue by HappyTreesDev** [LearnBoost/mongoose#2769]
I was looking to store a Code data type. All I was able to find was a plugin by aheckmann that stores functions as strings it seems. Why does mongoose not have the support for all of the different BSON types and is there a plan to add it in the future?

**Comment by vkarpov15** [comment]
As far as I know, [the "Code" type in BSON is just a plain string](http://bsonspec.org/spec.html). I think Aaron's [mongoose-function module](https://www.npmjs.com/package/mongoose-function) would probably be the right way to implement this atm.

**Comment by HappyTreesDev** [comment]
I did find Aaron's module, and that is what I am using atm, I was curious why it is not a part of Mongoose itself. Also, the "Code" type stores function scope along with the function, while Aaron's module does not in favor of allowing regex searching to still work. I am not sure which way mongoose would represent it, but I still feel that mongoose would benefit from supporting all of the BSON types somehow. Maybe its just me and the other types are too niche and are better off left as a plugin. It would be nice to have official plugins for them though then.

**Comment by vkarpov15** [comment]
The reason now is what you specified - the other types are a little niche and don't really match up well with how most people want to use mongoose in my experience. There is a plugin, but we don't really have a notion of an "official plugin" atm.

**Comment by HappyTreesDev** [comment]
Okay, that makes sense enough. It would be nice if somewhere it was noted that these plugins exist.

**Comment by vkarpov15** [comment]
Perhaps it would make sense to have a list of "highlighted plugins" or something like that on plugins.mongoosejs.com. Something else that's curated and not just "whatever's tagged with mongoose on npm." What do you think?

**Comment by Swissbite** [comment]
Why not use http://www.npcjs.io/#/?keyword=mongoose to see also github
watches, forkes and stars?

I know, camouflaged <http://www.dict.cc/englisch-deutsch/camouflaged.html>
advertising <http://www.dict.cc/englisch-deutsch/advertising.html>...

Valeri Karpov <notifications@github.com> schrieb am Mi., 18. März 2015 um
21:44 Uhr:

**Comment by vkarpov15** [comment]
Great suggestion :) does npcjs have a REST API?

**Comment by Swissbite** [comment]
It has. Currently without paging possibilities.

**Comment by HappyTreesDev** [comment]
The main thing I would personally want, is some form of category system possibly. When I first came into mongoose, I had no idea what kind of plugins existed and it would be nice to know what things exist, rather than having to have a need to know what to look for. Does that make sense?

**Comment by vkarpov15** [comment]
A fair point. With plugins it's difficult because often you don't really know what you're looking for or what to call it, and npm's search feature isn't great at filling in the blanks for you. I opened up a separate issue #2774 to track the discussion re: featured plugins
