### ISSUE TITLE
.distinct() documentation at mongoose API docs are misleading

### ISSUE THREAD

**Issue by inampaki** [LearnBoost/mongoose#2770]
http://mongoosejs.com/docs/api.html#query_Query-distinct
Please look into it documentation states that 1st parameter is criteria / query but when I am sending the Query to 1st argument it is not returning any results, after checking in Mongodb official documentation I tested it by sending the query as 2nd argument worked.

**Comment by vkarpov15** [comment]
Are you using 3.8 or 4.0? This order was reversed in 4.0 to be more consistent with mongodb, see [4.0 release notes](https://github.com/LearnBoost/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes).

**Comment by inampaki** [comment]
I am using 3.8.x, but I was using Model.distinct not Model.find().distinct(); any ways your answer clarified my misunderstanding.

**Comment by vkarpov15** [comment]
Yeah 3.8.x has this backwards in Model.find().distinct(). Not entirely sure why, but the docs reflect this difference. 4.0 makes this order consistent with mongodb server for both `Model.distinct()` and `Model.find().distinct()`
