### ISSUE TITLE
Can not assign mongoose object to a ref field - for subdocument instance

### ISSUE THREAD

**Issue by iq-dot** [LearnBoost/mongoose#2776]
So I have document where I retrieve a single sub-document instance, in that instance there is a ref field, however I already have retrieved the full object for that field, so I try to assign to it but it fails, i.e. it does not assign, it remains a ref field. I thought this works as the populate essential does this no?

So to show with an example:

My schema:
```
User: {
  events: [{
    sender: {
      type: Schema.ObjectId,
      ref: 'User'
    }
  }]
}
```

And my code:

```
var sender = User.findById(....) // I retrieve the sender
var event = user.events.id(id); // I retrieve the event by ID for the current user, a sub-document instance

// Now I want to do this but it doesn't work
event.sender = sender; // does not assign, it still remains an ObjectId
```

Am I doing anything wrong or is this a bug? Is there a way to do what I want? I know it is possible to do populate on a the whole sub-document array but for me that is inefficient as I want to do it on an single instance only and I already have the field that needs to be populated.

**Comment by vkarpov15** [comment]
You can do this in 4.0 - 4.0 supports this for single refs (as opposed to arrays of refs like `[Schema.ObjectId]`), so `npm install mongoose@unstable` should enable you to do this.

In 3.8 the only real workaround is to do `toObject()` on both event and sender, and then do the assignment. You can then send the correctly formatted object to the client.

**Comment by iq-dot** [comment]
Is there a readme somewhere that mentions any breaking changes in 4.0 going from 3.x?

**Comment by vkarpov15** [comment]
The [wiki has release notes](https://github.com/LearnBoost/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes) that should cover the extent of backwards breaking API changes. They're relatively minor but do exist.
